"""Collect rollouts/episodes from the FindGoal env and save them to disk for later use in training and evaluation."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/01a_data.collect.ipynb.

# %% auto #0
__all__ = []

# %% ../../nbs/01a_data.collect.ipynb #b6666a02
from fastcore import *
from fastcore.utils import *
