"""Collect rollouts/episodes from the FindGoal env and save them to disk for later use in training and evaluation."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/01a_data.collect.ipynb.

# %% auto #0
__all__ = ['normalize', 'generate_data_marl_grid_np', 'generate_data_marl_grid_h52', 'collect_one_rollout_h5',
           'combine_npz_files']

# %% ../../nbs/01a_data.collect.ipynb #b6666a02
from fastcore import *
from fastcore.utils import *

# %% ../../nbs/01a_data.collect.ipynb #f27cdf18
def normalize(img):
    return (img - img.min()) / (img.max() - img.min())


# %% ../../nbs/01a_data.collect.ipynb #23f8d256
import numpy as np
import os
from mawm.envs.marl_grid import make_env
from mawm.envs.marl_grid.cfg import config

def generate_data_marl_grid_np(
    rollouts=3,
    seed_steps=4000,
    data_dir='../marl_grid_data',
    save_metadata=True,      # NEW: save environment metadata
    env_name="marl_grid"
):
    """Generate and save full rollouts from a MarlGrid environment."""
    
    if not os.path.exists(data_dir):
        os.makedirs(data_dir)
    
    def create_env():
        config.env_cfg.seed = np.random.randint(0, 5) # use only small set of envs for training.
        config.env_cfg.max_steps = seed_steps
        env = make_env(config.env_cfg)
        agents = [f'agent_{i}' for i in range(config.env_cfg.num_agents)]
        return env, agents
    
    # Save config metadata once
    if save_metadata:
        meta_path = os.path.join(data_dir, "metadata.npz")
        np.savez_compressed(meta_path, 
                          grid_size=config.env_cfg.grid_size,
                          num_agents=config.env_cfg.num_agents,
                          max_steps=seed_steps,
                          view_size=config.env_cfg.view_size)
    
    for rollout_idx in range(rollouts):
        print(f"\nStarting rollout {rollout_idx}...")
        env, agents = create_env()
        
        # Fresh buffers for each rollout
        agent_data = {
            ag: {
                "obs":  [], 
                "selfpos": [], 
                "orientation": [],
                "sees_goal": [],
                "rew":  [], 
                "act":  [], 
                "done": [],  # Per-agent done status
            } for ag in agents
        }
        
        
        obs = env.reset()
        success = False
        success_at = -1
        goal_pos = obs['global']['goal_pos']
        # import ipdb; ipdb.set_trace()
        goal_obs = np.array([env.get_goal(env.agents[i], goal_pos)[0] for i in range(config.env_cfg.num_agents)])
        
        # Store initial observations
        for idx, ag in enumerate(agents):
            agent_data[ag]["obs"].append(obs[ag]['pov'])
            agent_data[ag]["selfpos"].append(obs[ag]['selfpos'])
            agent_data[ag]["orientation"].append(obs[ag]['orientation'])
            agent_data[ag]["sees_goal"].append(obs["global"]['sees_goal'][idx])
            agent_data[ag]["done"].append(False)  # Initial done status is False
        
        
        
        episode_len = 0
        
        for t in range(seed_steps):
            actions = {ag: env.action_space.sample() for ag in agents}
            obs, rew, done, info = env.step(actions)
            
            for ag in agents:
                agent_data[ag]["obs"].append(obs[ag]['pov'])
                agent_data[ag]["selfpos"].append(obs[ag]['selfpos'])
                agent_data[ag]["orientation"].append(obs[ag]['orientation'])
                agent_data[ag]["sees_goal"].append(info[ag]['sees_goal'])

                agent_data[ag]["rew"].append(rew[ag])
                agent_data[ag]["act"].append(actions[ag])
                agent_data[ag]["done"].append(info[ag]['done'])

                
            
            episode_len += 1
            
            if done['__all__']:
                success = True if all(info[ag]['done'] for ag in agents) else False
                success_at = t if success else -1
                print(f"> Rollout {rollout_idx} ended at step {t} (goal reached or timeout)")
                break
        
        # Save rollout
        save_path = os.path.join(data_dir, f"rollout_{rollout_idx}.npz")
        save_dict = {
            "episode_len": episode_len,
            "rng_state": env.np_random.bit_generator.state['state']['state'],  # Save RNG state for reproducibility
            "seed": config.env_cfg.seed,
            "goal_pos": goal_pos,
            "goal_obs": goal_obs,
            "success": success,
            "success_at": success_at
        }
        final_dict = {
            "global": np.array([save_dict]),
        }

        for agent in agents:
            final_dict[agent] = {
                "obs": np.stack(agent_data[agent]["obs"]),
                "selfpos": np.stack(agent_data[agent]["selfpos"]),
                "orientation": np.stack(agent_data[agent]["orientation"]),
                "sees_goal": np.stack(agent_data[agent]["sees_goal"]),

                "act": np.stack(agent_data[agent]["act"]),
                "rew": np.stack(agent_data[agent]["rew"]),
                "done": np.stack(agent_data[agent]["done"]),
            }
            print(np.stack(agent_data[agent]["obs"]).shape)
        
        
            
        np.savez_compressed(save_path, **final_dict)
        print(f"> Saved rollout {rollout_idx} ({episode_len} steps) to {save_path}")
        
        env.close()
    
    print(f"\nData generation complete! {rollouts} rollouts saved to {data_dir}")

# %% ../../nbs/01a_data.collect.ipynb #20fbac6d
import numpy as np
import os
import h5py
from mawm.envs.marl_grid import make_env
from mawm.envs.marl_grid.cfg import config


def generate_data_marl_grid_h52(
    rollouts=3,
    seed_steps=4000,
    data_dir="../marl_grid_data",
    env_name="marl_grid"
):

    os.makedirs(data_dir, exist_ok=True)

    def create_env():
        config.env_cfg.seed = np.random.randint(0, 5)
        config.env_cfg.max_steps = seed_steps
        env = make_env(config.env_cfg)
        agents = [f"agent_{i}" for i in range(config.env_cfg.num_agents)]
        return env, agents

    # ---- Save metadata ONCE ----
    meta_path = os.path.join(data_dir, "metadata.h5")
    if not os.path.exists(meta_path):
        with h5py.File(meta_path, "w") as f:
            f.attrs["grid_size"] = config.env_cfg.grid_size
            f.attrs["num_agents"] = config.env_cfg.num_agents
            f.attrs["max_steps"] = seed_steps
            f.attrs["view_size"] = config.env_cfg.view_size

    for rollout_idx in range(rollouts):
        print(f"\nStarting rollout {rollout_idx}...")

        env, agents = create_env()
        obs = env.reset()

        goal_pos = obs["global"]["goal_pos"]
        goal_obs = np.array(
            [env.get_goal(env.agents[i], goal_pos)[0]
             for i in range(config.env_cfg.num_agents)]
        )

        agent_data = {
            ag: {k: [] for k in
                 ["obs", "selfpos", "orientation", "sees_goal",
                  "act", "rew", "done"]}
            for ag in agents
        }

        # ---- initial observation ----
        for i, ag in enumerate(agents):
            agent_data[ag]["obs"].append(obs[ag]["pov"])
            agent_data[ag]["selfpos"].append(obs[ag]["selfpos"])
            agent_data[ag]["orientation"].append(obs[ag]["orientation"])
            agent_data[ag]["sees_goal"].append(obs["global"]["sees_goal"][i])
            agent_data[ag]["done"].append(False)

        episode_len = 0
        success = False
        success_at = -1

        for t in range(seed_steps):
            actions = {ag: env.action_space.sample() for ag in agents}
            obs, rew, done, info = env.step(actions)

            for ag in agents:
                agent_data[ag]["obs"].append(obs[ag]["pov"])
                agent_data[ag]["selfpos"].append(obs[ag]["selfpos"])
                agent_data[ag]["orientation"].append(obs[ag]["orientation"])
                agent_data[ag]["sees_goal"].append(info[ag]["sees_goal"])
                agent_data[ag]["act"].append(actions[ag])
                agent_data[ag]["rew"].append(rew[ag])
                agent_data[ag]["done"].append(info[ag]["done"])

            episode_len += 1
            if done["__all__"]:
                success = all(info[ag]["done"] for ag in agents)
                success_at = t if success else -1
                print(f"> Rollout {rollout_idx} ended at step {t} (goal reached or timeout), success: {success}")
                break

        env.close()

        # ---- WRITE HDF5 FILE ----
        save_path = os.path.join(data_dir, f"rollout_{rollout_idx}.h5")

        with h5py.File(save_path, "w") as f:

            # ---- global group ----
            g = f.create_group("global")
            g.create_dataset("episode_len", data=episode_len)
            g.create_dataset("goal_pos", data=goal_pos)
            g.create_dataset("goal_obs", data=goal_obs)
            g.create_dataset("success", data=success)
            g.create_dataset("success_at", data=success_at)
            g.attrs["seed"] = config.env_cfg.seed

            # ---- agents ----
            for ag in agents:
                ag_g = f.create_group(ag)

                for key, seq in agent_data[ag].items():
                    arr = np.stack(seq)
                    ag_g.create_dataset(
                        key,
                        data=arr,
                        compression="gzip",
                        compression_opts=4,
                        chunks=True
                    )

        print(f"> Saved rollout {rollout_idx} ({episode_len} steps) → {save_path}")

    print(f"\nData generation complete: {rollouts} rollouts saved.")


# %% ../../nbs/01a_data.collect.ipynb #0f85c527
import os
import numpy as np
import h5py
from mawm.envs.marl_grid import make_env
from mawm.envs.marl_grid.cfg import config

def collect_one_rollout_h5(args):
    rollout_idx, seed_steps, data_dir = args  

    config.env_cfg.seed = np.random.randint(0, 5)
    config.env_cfg.max_steps = seed_steps

    env = make_env(config.env_cfg)
    agents = [f"agent_{i}" for i in range(config.env_cfg.num_agents)]

    obs = env.reset()
    goal_pos = obs["global"]["goal_pos"]
    goal_obs = np.array(
            [env.get_goal(env.agents[i], goal_pos)[0]
             for i in range(config.env_cfg.num_agents)]
            )
    layout = env.get_layout(render_kwargs={"tile_size":11})

    agent_data = {
        ag: {k: [] for k in
             ["obs", "selfpos", "orientation", "sees_goal",
              "act", "rew", "done"]}
        for ag in agents
    }

    for i, ag in enumerate(agents):
        agent_data[ag]["obs"].append(obs[ag]["pov"])
        agent_data[ag]["selfpos"].append(obs[ag]["selfpos"])
        agent_data[ag]["orientation"].append(obs[ag]["orientation"])
        agent_data[ag]["sees_goal"].append(obs["global"]["sees_goal"][i])
        agent_data[ag]["done"].append(False)

    episode_len = 0
    success = False
    success_at = -1

    for t in range(seed_steps):
        actions = {ag: env.action_space.sample() for ag in agents}
        obs, rew, done, info = env.step(actions)

        for ag in agents:
            agent_data[ag]["obs"].append(obs[ag]["pov"])
            agent_data[ag]["selfpos"].append(obs[ag]["selfpos"])
            agent_data[ag]["orientation"].append(obs[ag]["orientation"])
            agent_data[ag]["sees_goal"].append(info[ag]["sees_goal"])
            agent_data[ag]["act"].append(actions[ag])
            agent_data[ag]["rew"].append(rew[ag])
            agent_data[ag]["done"].append(info[ag]["done"])

        episode_len += 1
        if done["__all__"]:
            success = all(info[ag]["done"] for ag in agents)
            success_at = t if success else -1
            break

    env.close()

    roolout_dir = os.path.join(data_dir, f"rollout_{rollout_idx}")
    os.makedirs(roolout_dir, exist_ok=True)
    save_path = os.path.join(roolout_dir, f"rollout_{rollout_idx}.h5")
    metadata_path = os.path.join(roolout_dir, "metadata.h5")

    with h5py.File(metadata_path, "w") as f:
        g = f.create_group("global")
        g.create_dataset("layout", data=layout)
        g.create_dataset("goal_pos", data=goal_pos)
        g.create_dataset("goal_obs", data=goal_obs)

        g.attrs["episode_len"] = episode_len
        g.attrs["success"] = success
        g.attrs["success_at"] = success_at
        g.attrs["seed"] = config.env_cfg.seed
        g.attrs["rng_state"] = str(env.np_random.bit_generator.state['state']['state'])
        
    f.close()
    with h5py.File(save_path, "w") as f:
        for ag in agents:
            ag_g = f.create_group(ag)
            for k, seq in agent_data[ag].items():
                ag_g.create_dataset(
                    k,
                    data=np.stack(seq),
                    compression="gzip",
                    chunks=True
                )
    f.close()
    
    return rollout_idx


# %% ../../nbs/01a_data.collect.ipynb #bd4e23bf
import numpy as np
from pathlib import Path

def combine_npz_files(meta_files, output_file="meta_data_merged.npz"):
    master_dict = {}

    for i, file_path in enumerate(meta_files):
        with np.load(file_path, allow_pickle=True) as data:
            for key in data.files:
                new_key = f"rollout_{i}_{key}"
                master_dict[new_key] = data[key]

    np.savez_compressed(output_file, **master_dict)
