"""This module handles all communication-related functionalities, including message passing, event handling, and notifications."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/01d_data.utils.ipynb.

# %% auto #0
__all__ = ['H_full_url', 'valid_2d_url', 'csi_data_url', 'gdown_download_file', 'get_h_full', 'get_valid_2d', 'get_csi_data',
           'np_get_csi', 'np_get_all_from', 'np_get_neighbors_csi', 'build_csi_index', 'df_get_csi', 'df_get_all_from',
           'df_get_neighbors_csi', 'save_rollout_hdf5', 'merge_npz_to_hdf5', 'show_batch']

# %% ../../nbs/01d_data.utils.ipynb #636bf21f
from fastcore import *
from fastcore.utils import *

# %% ../../nbs/01d_data.utils.ipynb #f7f6458c
import os

import numpy as np
import pandas as pd
import gdown

import torch
from torch.utils.data import DataLoader
import torchvision.transforms.v2 as v2
import torch.nn.functional as F

# %% ../../nbs/01d_data.utils.ipynb #48174c7d
def gdown_download_file(url: str, output: str= ".") -> None:
    """Downloads a file from the given URL and saves it to the specified output path.
    Args:
        url (str): The URL to download the file from.
        output (str): The path where the downloaded file should be saved.
    """
    gdown.download(url, output)

# %% ../../nbs/01d_data.utils.ipynb #d97d50f9
H_full_url = "https://drive.google.com/file/d/126gvv5GBgzgG21y19fza5vHBtFGxRWMq/view?usp=sharing"
valid_2d_url = "https://drive.google.com/file/d/1Dzj9joHNG434-ZQy3lIEBlscFvw_jH0w/view?usp=sharing"
csi_data_url = "https://drive.google.com/file/d/1bAQEiAvFU-oNeb_UuFO8nOD0NKaL08le/view?usp=sharing"


# %% ../../nbs/01d_data.utils.ipynb #2789bb20
def get_h_full(H_full_url: str = H_full_url) -> np.ndarray:
    gdown_download_file(H_full_url, "H_full.npy")
    return np.load("H_full.npy")

def get_valid_2d(valid_2d_url: str = valid_2d_url) -> list:
    gdown_download_file(valid_2d_url, "valid_2d.npy")
    return [tuple(p) for p in np.load("valid_2d.npy")]

def get_csi_data(csi_data_url: str = csi_data_url) -> pd.DataFrame:
    gdown_download_file(csi_data_url, "csi_data.csv")
    return pd.read_csv("csi_data.csv")


# %% ../../nbs/01d_data.utils.ipynb #dc4a5830
def np_get_csi(H_full: np.ndarray, grid_to_idx: dict, tx_grid: tuple, rx_grid: tuple) -> np.ndarray:
    """
    Get CFR for a D2D link between two grid positions.
    tx_grid, rx_grid: (gx, gy) tuples
    Returns: complex array of shape [num_subcarriers]
    """
    i = grid_to_idx[tx_grid]
    j = grid_to_idx[rx_grid]
    assert i != j, f"tx and rx are the same position: {tx_grid}"
    return H_full[j, i]

def np_get_all_from(H_full: np.ndarray, grid_to_idx: dict, tx_grid: tuple) -> dict:
    """All channels from a given tx position to every other valid position."""
    i = grid_to_idx[tx_grid]
    return {
        idx_to_grid[j]: H_full[j, i]
        for j in range(N) if j != i
    }

def np_get_neighbors_csi(H_full: np.ndarray, grid_to_idx: dict, tx_grid: tuple, radius: int = 1) -> dict:
    """Only get CSI to nearby grid positions (useful for local D2D)."""
    gx, gy = tx_grid
    result = {}
    for rx_grid in valid_2d:
        rx_gx, rx_gy = rx_grid
        if rx_grid == tx_grid:
            continue
        if abs(rx_gx - gx) <= radius and abs(rx_gy - gy) <= radius:
            result[rx_grid] = np_get_csi(H_full, grid_to_idx, tx_grid, rx_grid)
    return result



# %% ../../nbs/01d_data.utils.ipynb #01170486
# Assuming df has columns: tx_grid, rx_grid, csi
# and tuples are stored as (gx, gy)

# Build a lookup index from the dataframe once
def build_csi_index(csi_data: pd.DataFrame) -> dict:
    return {
        (tx, rx): csi
        for tx, rx, csi in zip(csi_data["tx_grid"], csi_data["rx_grid"], csi_data["csi"])
    }

def df_get_csi(csi_data: pd.DataFrame, tx_grid: tuple, rx_grid: tuple) -> complex:
    """Get CSI for a single tx->rx pair."""
    # Normalize to plain int tuples (in case of np.int64)
    csi_index = build_csi_index(csi_data)
    tx = (int(tx_grid[0]), int(tx_grid[1]))
    rx = (int(rx_grid[0]), int(rx_grid[1]))
    assert tx != rx, f"tx and rx are the same position: {tx}"
    print((tx, rx))
    return csi_index[(tx, rx)]

def df_get_all_from(csi_data: pd.DataFrame, tx_grid: tuple) -> pd.DataFrame:
    """All channels from a given tx position to every other valid position."""
    tx = (int(tx_grid[0]), int(tx_grid[1]))
    return csi_data[csi_data["tx_grid"].apply(lambda t: (int(t[0]), int(t[1])) == tx)]

def df_get_neighbors_csi(csi_data: pd.DataFrame, tx_grid: tuple, radius: int = 1) -> pd.DataFrame:
    """Only get CSI to nearby grid positions."""
    tx = (int(tx_grid[0]), int(tx_grid[1]))
    gx, gy = tx

    def is_neighbor(rx):
        rx = (int(rx[0]), int(rx[1]))
        return rx != tx and abs(rx[0] - gx) <= radius and abs(rx[1] - gy) <= radius

    mask = (
        csi_data["tx_grid"].apply(lambda t: (int(t[0]), int(t[1])) == tx) &
        csi_data["rx_grid"].apply(is_neighbor)
    )
    return csi_data[mask]

# %% ../../nbs/01d_data.utils.ipynb #84a11516
import os
import glob

import numpy as np
import h5py


# %% ../../nbs/01d_data.utils.ipynb #9bb0165e
def save_rollout_hdf5(rollout_idx, save_dict, data_dir):
    """Save one rollout as a group inside a shared HDF5 file."""
    os.makedirs(data_dir, exist_ok=True)
    h5_path = os.path.join(data_dir, "dataset.h5")

    with h5py.File(h5_path, 'a') as f:   # 'a' = append mode
        grp = f.create_group(f"rollout_{rollout_idx:06d}")
        for k, v in save_dict.items():
            grp.create_dataset(
                k,
                data=v if isinstance(v, np.ndarray) else np.asarray(v),
                compression="lz4",   # fast compression, good for uint8 images
            )

def merge_npz_to_hdf5(data_dir, out_path):
    files = sorted(glob.glob(os.path.join(data_dir, "rollout_*.npz")))

    merged = 0
    skipped = 0

    with h5py.File(out_path, "w") as h5:
        for fpath in files:

            try:
                with np.load(fpath, allow_pickle=True) as data:

                    # Force validation of every member
                    for k in data.files:
                        _ = data[k]

                    name = os.path.splitext(os.path.basename(fpath))[0]
                    grp = h5.create_group(name)

                    for k in data.files:
                        arr = data[k]

                        if arr.ndim == 0:
                            grp.attrs[k] = arr.item()
                        else:
                            grp.create_dataset(
                                k,
                                data=arr,
                                compression="gzip",
                                compression_opts=4,
                            )

                merged += 1

            except Exception as e:
                skipped += 1
                print(f"Skipping {fpath}: {e}")

    print(f"Merged  {merged} rollouts")
    print(f"Skipped {skipped} corrupted rollouts")
    

# %% ../../nbs/01d_data.utils.ipynb #392da375
import matplotlib.pyplot as plt
import numpy as np
import torchvision
import torch
import einops
def show_batch(dl, denormalize_tf, save_to="./batch.png"):
    dataiter = iter(dl)
    data = next(dataiter)
    images = data['agent_0']['obs']

    if images.ndim == 5:
        images = einops.rearrange(images, 'b s c h w -> (b s) c h w')
        print(images.shape)

    print(f"Max pixel value: {images.max().item()}")
    print(f"Mean pixel value: {images.mean().item()}")
    images = denormalize_tf(images) if denormalize_tf is not None else images
    print(f"After denormalization:")
    print("+"*20)
    print(f"Max pixel value: {images.max().item()}")
    print(f"Mean pixel value: {images.mean().item()}")
    images = torch.clamp(images, 0, 1)

    grid_img = torchvision.utils.make_grid(images, nrow=8) # nrow controls how many images per row
    np_grid = torch.einsum('chw->hwc', grid_img).numpy()


    plt.figure(figsize=(15, 10))
    plt.imshow(np_grid)
    plt.axis('off')
    plt.savefig(save_to, bbox_inches='tight')
    plt.savefig("pdf.pdf", bbox_inches='tight')
    plt.show()
