"""This module handles all communication-related functionalities, including message passing, event handling, and notifications."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/01c_data.utils.ipynb.

# %% auto #0
__all__ = ['H_full_url', 'valid_2d_url', 'csi_data_url', 'base_tf', 'denormalize_tf', 'lejepa_train_tf', 'lejepa_test_tf',
           'data_loader', 'gdown_download_file', 'get_h_full', 'get_valid_2d', 'get_csi_data', 'np_get_csi',
           'np_get_all_from', 'np_get_neighbors_csi', 'build_csi_index', 'df_get_csi', 'df_get_all_from',
           'df_get_neighbors_csi', 'get_data_path']

# %% ../../nbs/01c_data.utils.ipynb #0e7a0a27
from fastcore import *
from fastcore.utils import *

# %% ../../nbs/01c_data.utils.ipynb #c137cb02
import numpy as np
import pandas as pd
import torch
import gdown

# %% ../../nbs/01c_data.utils.ipynb #d7ebf77b
import pytorch_lightning as pl


## Utils to handle newer PyTorch Lightning changes from version 0.6
## ==================================================================================================== ##


def data_loader(fn):
    """
    Decorator to handle the deprecation of data_loader from 0.7
    :param fn: User defined data loader function
    :return: A wrapper for the data_loader function
    """

    def func_wrapper(self):
        try: # Works for version 0.6.0
            return pl.data_loader(fn)(self)

        except: # Works for version > 0.6.0
            return fn(self)

    return func_wrapper

# %% ../../nbs/01c_data.utils.ipynb #124a7ea5
def gdown_download_file(url: str, output: str= ".") -> None:
    """Downloads a file from the given URL and saves it to the specified output path.
    Args:
        url (str): The URL to download the file from.
        output (str): The path where the downloaded file should be saved.
    """
    gdown.download(url, output)

# %% ../../nbs/01c_data.utils.ipynb #94d9a00e
H_full_url = "https://drive.google.com/file/d/126gvv5GBgzgG21y19fza5vHBtFGxRWMq/view?usp=sharing"
valid_2d_url = "https://drive.google.com/file/d/1Dzj9joHNG434-ZQy3lIEBlscFvw_jH0w/view?usp=sharing"
csi_data_url = "https://drive.google.com/file/d/1bAQEiAvFU-oNeb_UuFO8nOD0NKaL08le/view?usp=sharing"


# %% ../../nbs/01c_data.utils.ipynb #3d7c1a6c
def get_h_full(H_full_url: str = H_full_url) -> np.ndarray:
    gdown_download_file(H_full_url, "H_full.npy")
    return np.load("H_full.npy")

def get_valid_2d(valid_2d_url: str = valid_2d_url) -> list:
    gdown_download_file(valid_2d_url, "valid_2d.npy")
    return [tuple(p) for p in np.load("valid_2d.npy")]

def get_csi_data(csi_data_url: str = csi_data_url) -> pd.DataFrame:
    gdown_download_file(csi_data_url, "csi_data.csv")
    return pd.read_csv("csi_data.csv")


# %% ../../nbs/01c_data.utils.ipynb #8ba65ee8
def np_get_csi(H_full: np.ndarray, grid_to_idx: dict, tx_grid: tuple, rx_grid: tuple) -> np.ndarray:
    """
    Get CFR for a D2D link between two grid positions.
    tx_grid, rx_grid: (gx, gy) tuples
    Returns: complex array of shape [num_subcarriers]
    """
    i = grid_to_idx[tx_grid]
    j = grid_to_idx[rx_grid]
    assert i != j, f"tx and rx are the same position: {tx_grid}"
    return H_full[j, i]

def np_get_all_from(H_full: np.ndarray, grid_to_idx: dict, tx_grid: tuple) -> dict:
    """All channels from a given tx position to every other valid position."""
    i = grid_to_idx[tx_grid]
    return {
        idx_to_grid[j]: H_full[j, i]
        for j in range(N) if j != i
    }

def np_get_neighbors_csi(H_full: np.ndarray, grid_to_idx: dict, tx_grid: tuple, radius: int = 1) -> dict:
    """Only get CSI to nearby grid positions (useful for local D2D)."""
    gx, gy = tx_grid
    result = {}
    for rx_grid in valid_2d:
        rx_gx, rx_gy = rx_grid
        if rx_grid == tx_grid:
            continue
        if abs(rx_gx - gx) <= radius and abs(rx_gy - gy) <= radius:
            result[rx_grid] = np_get_csi(H_full, grid_to_idx, tx_grid, rx_grid)
    return result



# %% ../../nbs/01c_data.utils.ipynb #447b6a84
# Assuming df has columns: tx_grid, rx_grid, csi
# and tuples are stored as (gx, gy)

# Build a lookup index from the dataframe once
def build_csi_index(csi_data: pd.DataFrame) -> dict:
    return {
        (tx, rx): csi
        for tx, rx, csi in zip(csi_data["tx_grid"], csi_data["rx_grid"], csi_data["csi"])
    }

def df_get_csi(csi_data: pd.DataFrame, tx_grid: tuple, rx_grid: tuple) -> complex:
    """Get CSI for a single tx->rx pair."""
    # Normalize to plain int tuples (in case of np.int64)
    csi_index = build_csi_index(csi_data)
    tx = (int(tx_grid[0]), int(tx_grid[1]))
    rx = (int(rx_grid[0]), int(rx_grid[1]))
    assert tx != rx, f"tx and rx are the same position: {tx}"
    print((tx, rx))
    return csi_index[(tx, rx)]

def df_get_all_from(csi_data: pd.DataFrame, tx_grid: tuple) -> pd.DataFrame:
    """All channels from a given tx position to every other valid position."""
    tx = (int(tx_grid[0]), int(tx_grid[1]))
    return csi_data[csi_data["tx_grid"].apply(lambda t: (int(t[0]), int(t[1])) == tx)]

def df_get_neighbors_csi(csi_data: pd.DataFrame, tx_grid: tuple, radius: int = 1) -> pd.DataFrame:
    """Only get CSI to nearby grid positions."""
    tx = (int(tx_grid[0]), int(tx_grid[1]))
    gx, gy = tx

    def is_neighbor(rx):
        rx = (int(rx[0]), int(rx[1]))
        return rx != tx and abs(rx[0] - gx) <= radius and abs(rx[1] - gy) <= radius

    mask = (
        csi_data["tx_grid"].apply(lambda t: (int(t[0]), int(t[1])) == tx) &
        csi_data["rx_grid"].apply(is_neighbor)
    )
    return csi_data[mask]

# %% ../../nbs/01c_data.utils.ipynb #14af98d4
import torch
from torchvision.transforms import v2
base_tf = v2.Compose([
    v2.ToPILImage(),
    v2.ToImage(),
    v2.ToDtype(torch.float32, scale=True),
    v2.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5]),
])

denormalize_tf = v2.Compose([
    v2.Normalize(mean=[0., 0., 0.], std=[1/0.5, 1/0.5, 1/0.5]),
    v2.Normalize(mean=[-0.5, -0.5, -0.5], std=[1., 1., 1.]),
])

# %% ../../nbs/01c_data.utils.ipynb #268d15ce
import torch
from torchvision.transforms import v2
lejepa_train_tf = v2.Compose(
    [
        v2.ToPILImage(),
        v2.RandomResizedCrop(42, scale=(0.8, 1.0)), 
        v2.RandomApply([v2.ColorJitter(0.4, 0.4, 0.4, 0.1)], p=0.8),
        v2.RandomGrayscale(p=0.2),
        v2.RandomApply([v2.GaussianBlur(kernel_size=3, sigma=(0.1, 2.0))], p=0.1),
        v2.RandomHorizontalFlip(),
        v2.ToImage(),
        v2.ToDtype(torch.float32, scale=True),
        v2.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5]),
    ]
)


lejepa_test_tf = v2.Compose(
            [
                v2.ToPILImage(),
                v2.Resize(42),
                v2.CenterCrop(42),
                v2.ToImage(),
                v2.ToDtype(torch.float32, scale=True),
                v2.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5]),
            ]
        )

# %% ../../nbs/01c_data.utils.ipynb #408ef6e2
import os
def get_data_path():
    paths = {
        "kaggle": "/kaggle/input/marlgridv3/MarlGridV3/",
        "puhti": "/scratch/project_2009050/datasets/MarlGridV3/",
        "mahti": "/scratch/project_2009050/datasets/MarlGridV3/",
        "triton": "/scratch/work/sehadn1/MarlGridV3/",
        "local": "/home/ahmed//Ahmed-home/1- Projects/Research/Journal 2/Code/mawm/nbs/data_test/",
        "local_full": "/home/ahmed//Ahmed-home/Downloads/data/MarlGridV3/"
    }

    for hostname, path in paths.items():
        if os.path.exists(path):
            print(f"Data path found for hostname: {hostname}")
            return path
    raise FileNotFoundError("No valid data path found for this hostname.")

