# configs/eval/pipeline/eval.yaml
defaults:
  - /datamodule: jepa_data
  - /model@model.vqvae: vqvae
  - /model@model.jepa: control_jepa
  - _self_

stage: 3

# Define Stage 2 specific hyperparameters here
lr: 1e-4
wm_lr: 1e-4
power_lr: 3e-4
max_epochs: 100
num_workers: 6
train_split: 0.9
seed: 3072
img_size: 224
embed_dim: 192
msg_embedding_dim: 256
num_embeddings: 256
history_size: 3

model:
  vqvae:
    checkpoint_path: ??? #"" # "/scratch/project_2009050/expirements/findgoal/checkpoints/vqvae_pretraining/job_default_job/agent_vqvae_trainer/best_state_step_8_acc_-0.0057.pt" #"" #"${logging_params.ckp_dir}/best_vqvae.pt" # Interpolates the global ckp_dir!
  jepa:
    checkpoint_path: ??? # "/projappl/project_2009050/c3jepa-wm/mains/checkpoints/c3jepa_wm/job_34741815/agent_vqvae_trainer/best_state_step_7_acc_-0.3554.pt"

evaluator:
  _target_: c3jepa_wm.evaluators.jepa.MultiAgentGoalEvaluator
  history_size: ${pipeline.history_size} # Automatically grabs 3
  goal_offset: 10
  SNR: 10.0
  p_max: 10
  noise_power: 0.001
  device: "cuda"

planner: 
  _target_: c3jepa_wm.planners.mpc.JEPAGoalPlanner
  horizon: ${pipeline.history_size}
  history_size: ${pipeline.history_size}
  action_dim: 4
  pop_size: 300
  topk: 30
  opt_steps: 30  


eval_func:
  _target_: c3jepa_wm.evaluators.jepa.MultiAgentGoalEvaluator.evaluate_dataset_fixed_t0
  num_episodes: 30