"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/05c_trainers.control.ipynb.

# %% auto #0
__all__ = ['WMTrainer']

# %% ../../nbs/05c_trainers.control.ipynb #67669c5e
class WMTrainer:
    def __init__(self, cfg):
        self.cfg = cfg
