# configs/config.yaml
defaults:
  - pipeline: vqvae_pretrain
  - _self_

exp_params:
  manual_seed: 1234

logging_params:
  project_name: "vqvae_pretraining"
  save_dir: "/scratch/project_2009050/expirements/findgoal/logs"
  ckp_dir: "/scratch/project_2009050/expirements/findgoal/checkpoints" #"/home/ahmed/Downloads/"