# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/c3jepa-wm',
                'doc_host': 'https://Ahmed-Khaled-Saleh.github.io',
                'git_url': 'https://github.com/Ahmed-Khaled-Saleh/c3jepa-wm',
                'lib_path': 'c3jepa_wm'},
  'syms': {'c3jepa_wm.core': {'c3jepa_wm.core.foo': ('core.html#foo', 'c3jepa_wm/core.py')}}}
