"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05c_trainers.control.ipynb.

# %% auto #0
__all__ = []

# %% ../nbs/05c_trainers.control.ipynb #67a6be0c
#| export

