"""Various utility functions and helpers used across the project."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_utils.ipynb.

# %% auto #0
__all__ = ['H_full_url', 'valid_2d_url', 'csi_data_url', 'download_file', 'get_h_full', 'get_valid_2d', 'get_csi_data',
           'np_get_csi', 'np_get_all_from', 'np_get_neighbors_csi', 'build_csi_index', 'df_get_csi', 'df_get_all_from',
           'df_get_neighbors_csi']

# %% ../nbs/04_utils.ipynb #85e65c31
import numpy as np
import pandas as pd
import torch
import gdown

# %% ../nbs/04_utils.ipynb #016966d0
def download_file(url: str, output: str= ".") -> None:
    """Downloads a file from the given URL and saves it to the specified output path.
    Args:
        url (str): The URL to download the file from.
        output (str): The path where the downloaded file should be saved.
    """
    gdown.download(url, output)

# %% ../nbs/04_utils.ipynb #abf5cb4d
H_full_url = "https://drive.google.com/file/d/126gvv5GBgzgG21y19fza5vHBtFGxRWMq/view?usp=sharing"
valid_2d_url = "https://drive.google.com/file/d/1Dzj9joHNG434-ZQy3lIEBlscFvw_jH0w/view?usp=sharing"
csi_data_url = "https://drive.google.com/file/d/1bAQEiAvFU-oNeb_UuFO8nOD0NKaL08le/view?usp=sharing"


# %% ../nbs/04_utils.ipynb #f4e32cbe
def get_h_full(H_full_url: str = H_full_url) -> np.ndarray:
    download_file(H_full_url, "H_full.npy")
    return np.load("H_full.npy")

def get_valid_2d(valid_2d_url: str = valid_2d_url) -> list:
    download_file(valid_2d_url, "valid_2d.npy")
    return [tuple(p) for p in np.load("valid_2d.npy")]

def get_csi_data(csi_data_url: str = csi_data_url) -> pd.DataFrame:
    download_file(csi_data_url, "csi_data.csv")
    return pd.read_csv("csi_data.csv")


# %% ../nbs/04_utils.ipynb #9a9afb3f
def np_get_csi(H_full: np.ndarray, grid_to_idx: dict, tx_grid: tuple, rx_grid: tuple) -> np.ndarray:
    """
    Get CFR for a D2D link between two grid positions.
    tx_grid, rx_grid: (gx, gy) tuples
    Returns: complex array of shape [num_subcarriers]
    """
    i = grid_to_idx[tx_grid]
    j = grid_to_idx[rx_grid]
    assert i != j, f"tx and rx are the same position: {tx_grid}"
    return H_full[j, i]

def np_get_all_from(H_full: np.ndarray, grid_to_idx: dict, tx_grid: tuple) -> dict:
    """All channels from a given tx position to every other valid position."""
    i = grid_to_idx[tx_grid]
    return {
        idx_to_grid[j]: H_full[j, i]
        for j in range(N) if j != i
    }

def np_get_neighbors_csi(H_full: np.ndarray, grid_to_idx: dict, tx_grid: tuple, radius: int = 1) -> dict:
    """Only get CSI to nearby grid positions (useful for local D2D)."""
    gx, gy = tx_grid
    result = {}
    for rx_grid in valid_2d:
        rx_gx, rx_gy = rx_grid
        if rx_grid == tx_grid:
            continue
        if abs(rx_gx - gx) <= radius and abs(rx_gy - gy) <= radius:
            result[rx_grid] = np_get_csi(H_full, grid_to_idx, tx_grid, rx_grid)
    return result



# %% ../nbs/04_utils.ipynb #43cd390b
# Assuming df has columns: tx_grid, rx_grid, csi
# and tuples are stored as (gx, gy)

# Build a lookup index from the dataframe once
def build_csi_index(csi_data: pd.DataFrame) -> dict:
    return {
        (tuple(tx), tuple(rx)): csi
        for tx, rx, csi in zip(csi_data["tx_grid"], csi_data["rx_grid"], csi_data["csi"])
    }

def df_get_csi(csi_data: pd.DataFrame, tx_grid: tuple, rx_grid: tuple) -> complex:
    """Get CSI for a single tx->rx pair."""
    # Normalize to plain int tuples (in case of np.int64)
    csi_index = build_csi_index(csi_data)
    tx = (int(tx_grid[0]), int(tx_grid[1]))
    rx = (int(rx_grid[0]), int(rx_grid[1]))
    assert tx != rx, f"tx and rx are the same position: {tx}"
    return csi_index[(tx, rx)]

def df_get_all_from(csi_data: pd.DataFrame, tx_grid: tuple) -> pd.DataFrame:
    """All channels from a given tx position to every other valid position."""
    tx = (int(tx_grid[0]), int(tx_grid[1]))
    return csi_data[csi_data["tx_grid"].apply(lambda t: (int(t[0]), int(t[1])) == tx)]

def df_get_neighbors_csi(csi_data: pd.DataFrame, tx_grid: tuple, radius: int = 1) -> pd.DataFrame:
    """Only get CSI to nearby grid positions."""
    tx = (int(tx_grid[0]), int(tx_grid[1]))
    gx, gy = tx

    def is_neighbor(rx):
        rx = (int(rx[0]), int(rx[1]))
        return rx != tx and abs(rx[0] - gx) <= radius and abs(rx[1] - gy) <= radius

    mask = (
        csi_data["tx_grid"].apply(lambda t: (int(t[0]), int(t[1])) == tx) &
        csi_data["rx_grid"].apply(is_neighbor)
    )
    return csi_data[mask]
