# configs/model/power_net.yaml
_target_: c3jepa_wm.models.power_net.PowerNet # Full absolute python import path

csi_dim: 1
embedding_dim: 256
num_embeddings: 256
max_power: 10
nhead: 4
num_layers: 2

