# data_params:
#   data_path: "Data/"
#   train_batch_size: 64
#   val_batch_size:  64
#   patch_size: 64
#   num_workers: 4


# data_path: "/scratch/project_2009050/datasets/findgoal/dataset.h5"
# val_ratio: 0.1
train_batch_size: 64
val_batch_size: 64
num_workers: 0