"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/07b_evaluators.jepa.ipynb.

# %% auto #0
__all__ = ['MultiAgentGoalEvaluator']

# %% ../../nbs/07b_evaluators.jepa.ipynb #b9bb9ea2
from collections import defaultdict
from typing import Any, Callable

import torch
import torch.nn.functional as F
import numpy as np
from einops import rearrange
import hydra
import wandb
from fastcore.utils import patch

from ..utils import channel
from ..utils.env_utils import MultiAgentEnvPool, set_env_state


# %% ../../nbs/07b_evaluators.jepa.ipynb #37e9a9d5
class MultiAgentGoalEvaluator:
    """
    Dataset-driven evaluation of the JEPA planner for a 2-agent communicative
    setting, driven through a `MultiAgentEnvPool` of N independent
    multi-agent envs -- one env instance per episode evaluated in parallel,
    mirroring `World._evaluate_from_dataset`'s `num_envs == len(episodes_idx)`
    pattern.

    For each agent, planning is now genuinely BATCHED across all N episodes
    in a chunk (a single `planner.plan(info[agent])` call handles all of
    them), rather than looping episodes one at a time at batch size 1.

    Args:
        model: JEPA model (has .encoder, .predictor, .action_encoder, .get_cost, .rollout)
        vqvae: sender-side VQ-VAE module; vqvae.encode(pixels) -> (B, 1, 49) token indices
        planner_cfg: hydra config to instantiate one planner per agent
        history_size: number of past steps fed as context (matches JEPA.rollout's history_size)
        goal_offset: number of steps ahead the goal is set
        agents: list of agent ids, must have length 2 (should match each
            env's `possible_agents`)
        device: torch device
        noop_action: action substituted for an agent that has reached its
            goal but whose env still expects an action from it every step.
    """

    def __init__(
        self,
        data_module,
        model,
        planner_cfg,
        slurm_jobid= None,
        history_size=3,
        goal_offset=10,
        dataset_agent_keys=None,
        agents=(0, 1),
        device="cpu",
        SNR=10.0,
        p_max=10,
        noise_power=1e-3,
        noop_action=3,
    ):
        assert len(agents) == 2, "This evaluator only supports exactly 2 agents."
        self.data_module = data_module
        self.data_module.setup()

        self.model = model['jepa'].to(device).eval()
        self.vqvae = model['vqvae'].to(device).eval()

        # env-side ids (ints, e.g. 0/1 -- match PettingZooWrapper's agent.index)
        self.agents = list(agents)
        # dataset-side keys (strings, e.g. "agent_0"/"agent_1" -- match batch dict columns)
        self.dataset_agent_keys = (
            dict(dataset_agent_keys) if dataset_agent_keys is not None
            else {a: f"agent_{a}" for a in self.agents}
        )

        self.history_size = history_size
        self.goal_offset = goal_offset
        self.device = device
        self.SNR = SNR
        self.p_max = p_max
        self.noise_power = noise_power
        self.noop_action = noop_action

        self.planners = {
            agent: hydra.utils.instantiate(planner_cfg, model=self.model, device=device)
            for agent in self.agents
        }


# %% ../../nbs/07b_evaluators.jepa.ipynb #f806a7d2
@patch
@torch.no_grad()
def _encode_message(self: MultiAgentGoalEvaluator, partner_pixels_vqvae_t0, csi_t0, schedule=None, power=None, no_comm=False):
    """
    partner_pixels_vqvae_t0: (B, C, H, W) -- partner's obs at t0, VQ-VAE-transform space
    csi_t0: (B,) complex -- channel state at t0 for this sender->receiver link
    schedule, power: (B,) tensors, or None to skip channel entirely
    """
    partner_pixels_vqvae_t0 = partner_pixels_vqvae_t0.to(self.device)
    indices = self.vqvae.get_message_indices(partner_pixels_vqvae_t0)  # (B, 1, H, W)
    indices = rearrange(indices, "B H W -> B (H W)").long()  # (B, 49)

    if schedule is not None and power is not None:
        csi = csi_t0.to(self.device)
        schedule = torch.as_tensor(schedule, device=self.device)
        power = torch.as_tensor(power, device=self.device)

        indices = channel(
            schedule=schedule,
            power=power,
            msg_indices=indices,
            csi=csi,
            device=self.device,
            snr_db=self.SNR,
            no_comm=no_comm,
        )

    return indices.unsqueeze(1)  # (B, 1, 49)


# %% ../../nbs/07b_evaluators.jepa.ipynb #6524bd5c
@patch
def _extract_power_and_schedule(self: MultiAgentGoalEvaluator, csi):
    snr_linear = 10 ** (self.SNR / 10.0)
    optimal_power = snr_linear * self.noise_power / (torch.abs(csi) ** 2 + 1e-8)
    schedule = (optimal_power <= self.p_max).float()
    return optimal_power, schedule


# %% ../../nbs/07b_evaluators.jepa.ipynb #044f01ef
@patch
def _build_agent_info_batch(self: MultiAgentGoalEvaluator, episodes: dict, agent, partner):
    """Build a batched info dict for `agent` across a chunk of episodes.

    episodes[agent][key]: already-windowed tensors with leading batch
    dim N (sliced to fixed size per episode at buffer-build time, then
    concatenated across the chunk) -- no per-episode t0 indexing needed
    here anymore.
    """
    pixels = episodes[agent]["pixels_hist"]
    actions = episodes[agent]["action_hist"]
    goal_pixels = episodes[agent]["goal_pixels"]

    partner_obs_vqvae_t0 = episodes[partner]["pov_vqvae_t0"]
    csi_t0 = episodes[partner]["csi_t0"].to(self.device)
    power_level, schedule = self._extract_power_and_schedule(csi_t0)
    msg_indices = self._encode_message(partner_obs_vqvae_t0, csi_t0, schedule=schedule, power=power_level)

    return {
        "pixels": pixels.to(self.device),
        "action": actions.to(self.device),
        "goal": goal_pixels.to(self.device),
        "msg_indices": msg_indices.to(self.device),
    }



# %% ../../nbs/07b_evaluators.jepa.ipynb #59668beb
@patch
@torch.no_grad()
def evaluate_batch_fixed_t0(self: MultiAgentGoalEvaluator, episodes: dict, pool: MultiAgentEnvPool, t0s, max_steps=150):
    """
    Evaluate a chunk of N episodes IN PARALLEL, using receding-horizon MPC:
    at every real environment step, run one batched CEM plan per agent
    (covering all N episodes at once) and execute only the first action
    of each. Repeats for up to max_steps real steps.

    Args:
        episodes: dict with "goal_pos" (N, ...), "goal_obs" (N, num_agents, ...),
            and per-agent sub-dicts each holding (N, T, ...) tensors, as
            produced by stacking single-episode batches from the dataloader.
        pool: MultiAgentEnvPool with `pool.num_envs == N`.
        t0s: (N,) int array/tensor of start steps, one per episode.
        max_steps: real-env step budget.

    Messaging: partner message is used only for the very first planning
    call at t0; dropped for all subsequent replanning calls.
    """
    H = self.history_size
    N = pool.num_envs
    t0s = np.asarray(t0s)
    assert (t0s >= H - 1).all(), f"t0 too early for history_size={H}"

    # --- fixed goal embeddings, batched over N episodes, per agent ---
    goal_emb = {}
    for ai, agent in enumerate(self.agents):
        g = episodes["goal_obs"][:, ai].unsqueeze(1).to(self.device)  # (N, 1, C, H, W)
        enc = self.model.encode({"pixels": g})
        goal_emb[agent] = enc["emb"][:, 0]  # (N, D)

    # --- reset all N envs, then force each to its recorded state at its t0 ---
    pool.reset(seed=0)
    goal_pos_list = episodes["goal_pos"].tolist()
    for i in range(N):
        agent_positions = {
            a: episodes[a]["pos_t0"][i].tolist() for a in self.agents
        }
        agent_directions = {
            a: int(episodes[a]["dir_t0"][i].item()) for a in self.agents
        }
        set_env_state(pool, i, goal_pos_list[i], agent_positions, agent_directions, self.agents)

    # --- initial per-agent batched info (includes message, used once) ---
    info = {}
    for agent in self.agents:
        partner = [a for a in self.agents if a != agent][0]
        info[agent] = self._build_agent_info_batch(episodes, agent, partner)

    results = {agent: {"step": [], "embedding_dist_to_goal": [], "reached": []} for agent in self.agents}

    # per-agent, per-episode alive mask -- True while that agent in that
    # episode still needs stepping (mirrors World._run_iter's `alive`).
    alive = {agent: np.ones(N, dtype=bool) for agent in self.agents}

    for real_step in range(max_steps):
        # env-level mask: skip envs where BOTH agents are done, for efficiency
        env_mask = alive[self.agents[0]] | alive[self.agents[1]]
        if not env_mask.any():
            break

        actions = {}
        for agent in self.agents:
            # full-batch replan every step (planner itself is unchanged --
            # no per-episode slicing here, matching the current design);
            # done agents' actions get overwritten with noop below.
            _, plan = self.planners[agent].plan(info[agent])  # (N, horizon)
            act = plan[:, 0].cpu().numpy()
            act = np.where(alive[agent], act, self.noop_action)
            actions[agent] = act

        _, rewards, terminateds, truncateds, stacked_infos = pool.step(
            actions, mask=env_mask, noop_action=self.noop_action
        )

        for agent in self.agents:
            for i in range(N):
                if not alive[agent][i] or not env_mask[i]:
                    continue

                pov = stacked_infos[agent]["pov"][i, 0]
                frame = self.data_module.val_receiver_transform(pov).unsqueeze(0).unsqueeze(0).to(self.device)
                enc = self.model.encode({"pixels": frame})
                cur_emb = enc["emb"][:, 0]

                dist = F.mse_loss(cur_emb, goal_emb[agent][i:i + 1], reduction="none").sum(-1)
                reached = tuple(pool.envs[i].env.unwrapped.agents[agent].state.pos) == tuple(goal_pos_list[i])

                results[agent]["step"].append((i, real_step))
                results[agent]["embedding_dist_to_goal"].append(dist.item())
                results[agent]["reached"].append(reached)

                new_action = torch.tensor([[actions[agent][i]]], device=self.device)
                info[agent]["pixels"][i] = torch.cat(
                    [info[agent]["pixels"][i, 1:], frame[0]], dim=0
                )
                info[agent]["action"][i] = torch.cat(
                    [info[agent]["action"][i, 1:], new_action].unsqueeze(1), dim=0
                ).squeeze()

                if reached:
                    alive[agent][i] = False

        # msg_indices only used on the very first planning call
        for agent in self.agents:
            info[agent].pop("msg_indices", None)

    return results



# %% ../../nbs/07b_evaluators.jepa.ipynb #4fb6fb73
@patch
@torch.no_grad()
def evaluate_dataset_fixed_t0(self: MultiAgentGoalEvaluator, make_env: Callable[[], Any],
                                num_episodes=None, max_steps=150, t0=None,
                                batch_size=8):
    """
    Runs evaluate_batch_fixed_t0 over chunks of `batch_size` episodes from
    the val dataset (each chunk run in parallel through its own
    MultiAgentEnvPool), aggregating embedding distance-to-goal and
    success by real step index across all episodes.

    Args:
        make_env: zero-arg factory building one fresh multi-agent env
            instance (e.g. `lambda: PettingZooWrapper(MultiGridEnv(...))`).
            Called `batch_size` times to build the pool.
        batch_size: number of episodes evaluated in parallel per chunk
            (mirrors CEMSolver's own `batch_size` chunking convention).
        t0: if None, defaults to history_size - 1 per episode. If an int,
            used as a fixed absolute t0 for every episode (episodes too
            short for it are skipped).

    NOTE: assumes the dataloader yields batch_size=1 (single episode per
    batch); episodes are buffered here and stacked into chunks of
    `batch_size` before being handed to the pool.
    """
    dataset = self.data_module.val_dataloader()
    assert dataset.batch_size == 1, "evaluate_dataset_fixed_t0 requires the dataloader's own batch_size=1"

    per_agent_step_dist = {agent: defaultdict(list) for agent in self.agents}
    per_agent_step_success = {agent: defaultdict(list) for agent in self.agents}

    pool = MultiAgentEnvPool([make_env for _ in range(batch_size)], agents=self.agents)

    n_evaluated = 0
    chunk_buffer = []

    def flush_chunk(chunk):
        nonlocal n_evaluated
        n = len(chunk)
        episodes = {
            "goal_pos": torch.stack([c["goal_pos"] for c in chunk]),
            "goal_obs": torch.stack([c["goal_obs"] for c in chunk]),
        }
        for agent in self.agents:
            episodes[agent] = {
                k: torch.cat([c[agent][k] for c in chunk], dim=0)
                for k in chunk[0][agent]
            }
        t0s = np.array([c["t0"] for c in chunk])

        # pool was built for `batch_size`; if this is a short final chunk,
        # only use the first `n` env slots.
        sub_pool = pool if n == pool.num_envs else _SubPool(pool, n)

        ep_res = self.evaluate_batch_fixed_t0(episodes, sub_pool, t0s, max_steps=max_steps)
        n_evaluated += n
        for agent in self.agents:
            for (i, step), dist, reached in zip(
                ep_res[agent]["step"], ep_res[agent]["embedding_dist_to_goal"], ep_res[agent]["reached"]
            ):
                per_agent_step_dist[agent][step].append(dist)
                per_agent_step_success[agent][step].append(float(reached))

    for i, batch in enumerate(dataset):
        if num_episodes is not None and n_evaluated + len(chunk_buffer) >= num_episodes:
            break

        length = batch["length"][0].item()
        this_t0 = (self.history_size - 1) if t0 is None else t0
        if this_t0 >= length:
            print(f"Skipping episode {i}: length={length} too short for t0={this_t0}")
            continue

        episode = {
            "goal_pos": batch["goal_pos"][0],
            "goal_obs": batch["goal_obs"][0],
            "t0": this_t0,
        }
        H = self.history_size
        goal_obs = episode["goal_obs"]  # (num_agents, C, H, W) or (num_agents, 1, C, H, W)
        for ai, agent in enumerate(self.agents):
            a_batch = batch[self.dataset_agent_keys[agent]]
            goal_frame = goal_obs[ai] if goal_obs.dim() == 5 else goal_obs[ai:ai + 1]
            # Slice down to fixed-size windows HERE, per episode, before
            # any cross-episode concatenation -- episode lengths vary
            # (that's what caused the cat() size mismatch), but a
            # history window of length H and single-step slices at t0
            # are the same size for every episode.
            episode[agent] = {
                "pixels_hist": a_batch["pixels"][0:1, this_t0 - H + 1: this_t0 + 1],
                "action_hist": a_batch["action"][0:1, this_t0 - H + 1: this_t0 + 1],
                "goal_pixels": goal_frame,  # (1, C, H, W): real dataset goal, matches original goal_override
                "pos_t0": a_batch["pos"][0:1, this_t0],
                "dir_t0": a_batch["dir"][0:1, this_t0],
                "pov_vqvae_t0": a_batch["pov_seq_vqvae"][0:1, this_t0],
                "csi_t0": a_batch["csi"][0:1, this_t0],
            }
        chunk_buffer.append(episode)

        if len(chunk_buffer) == batch_size:
            print(f"Evaluating chunk of {batch_size} episodes in parallel (max_steps={max_steps})...")
            flush_chunk(chunk_buffer)
            chunk_buffer = []

    if chunk_buffer:
        print(f"Evaluating final chunk of {len(chunk_buffer)} episodes in parallel...")
        flush_chunk(chunk_buffer)

    curves = {}
    for agent in self.agents:
        steps = sorted(per_agent_step_dist[agent].keys())
        curves[agent] = {
            "step": steps,
            "mean_embedding_dist": [float(torch.tensor(per_agent_step_dist[agent][s]).mean()) for s in steps],
            "std_embedding_dist": [float(torch.tensor(per_agent_step_dist[agent][s]).std()) for s in steps],
            "success_rate": [float(torch.tensor(per_agent_step_success[agent][s]).mean()) for s in steps],
        }

    for agent in self.agents:
        c = curves[agent]
        wandb.log({
            f"eval/{agent}/embedding_dist_vs_realstep": wandb.plot.line(
                wandb.Table(data=list(zip(c["step"], c["mean_embedding_dist"])), columns=["step", "mean_dist"]),
                x="step", y="mean_dist", title=f"{agent} embedding distance to goal vs real step (fixed t0)",
            ),
            f"eval/{agent}/success_rate_vs_realstep": wandb.plot.line(
                wandb.Table(data=list(zip(c["step"], c["success_rate"])), columns=["step", "success_rate"]),
                x="step", y="success_rate", title=f"{agent} cumulative success rate vs real step (fixed t0)",
            ),
        })

    return curves


# %% ../../nbs/07b_evaluators.jepa.ipynb #e011ae3f
class _SubPool:
    """Thin view exposing only the first `n` env slots of a larger pool, for
    a short final chunk that doesn't fill the whole pool. Avoids rebuilding
    (and re-instantiating, which may be expensive) the pool for the tail end
    of a dataset that isn't an exact multiple of batch_size."""
 
    def __init__(self, pool: MultiAgentEnvPool, n: int):
        self._pool = pool
        self._n = n
 
    @property
    def num_envs(self):
        return self._n
 
    @property
    def envs(self):
        return self._pool.envs[: self._n]
 
    def reset(self, seed=None, options=None, mask=None):
        full_mask = np.zeros(self._pool.num_envs, dtype=bool)
        full_mask[: self._n] = True if mask is None else mask
        return self._pool.reset(seed=seed, options=options, mask=full_mask)
 
    def step(self, actions, mask=None, noop_action= 3):
        full_mask = np.zeros(self._pool.num_envs, dtype=bool)
        full_mask[: self._n] = True if mask is None else mask
        full_actions = {
            a: np.concatenate([v, np.zeros(self._pool.num_envs - self._n, dtype=v.dtype)])
            for a, v in actions.items()
        }
        return self._pool.step(full_actions, mask=full_mask, noop_action=noop_action)
 


