"""This module handles all data/model/trainer loading logic based on the pipeline config. It provides a clean interface for the main training script, abstracting away the details of how different components are instantiated."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/06a_utils.__init__.ipynb.

# %% auto #0
__all__ = ['init_data', 'get_ckp_path', 'init_model', 'init_trainer', 'init_evaluator', 'channel', 'compute_power_schedule',
           'apply_channel', 'channel_optimal', 'PhaseTransitionChecker']

# %% ../../nbs/06a_utils.__init__.ipynb #def840ca
from fastcore import *
from fastcore.utils import *

# %% ../../nbs/06a_utils.__init__.ipynb #0a293b0f
from omegaconf import OmegaConf, DictConfig
import hydra
import torch
from torch import nn
from einops import rearrange
import math

# %% ../../nbs/06a_utils.__init__.ipynb #2ebf1235
def init_data(cfg: DictConfig):
    """Instantiates the correct datamodule based on the pipeline config."""
    print(f"Initializing Datamodule: {cfg.pipeline.datamodule._target_}")
    return hydra.utils.instantiate(cfg.pipeline.datamodule)


# %% ../../nbs/06a_utils.__init__.ipynb #e6785f24
def get_ckp_path(model_name):
    ckp_path = {
    "jepa":
        {
            "new_local": "/home/ahmed/Downloads/best_state_step_5_acc_-0.3516.pt",
            "local": "/home/ahmed/Ahmed-home/1- Projects/Research/Journal 2/code/c3jepa-wm/0_results/checkpoints/best_state_step_7_acc_-0.3554.pt",
            # "new_puhti": "/projappl/project_2009050/c3jepa-wm/mains/checkpoints/c3jepa_wm/job_35447252/agent_WM_trainer/best_state_step_12_acc_-0.3411.pt",
            "new_puhti": "/projappl/project_2009050/c3jepa-wm/mains/checkpoints/c3jepa_wm/job_35447252/agent_WM_trainer/last_state.pt",
            "puhti": "/projappl/project_2009050/c3jepa-wm/mains/checkpoints/c3jepa_wm/job_34741815/agent_vqvae_trainer/best_state_step_7_acc_-0.3554.pt"
        },
    "vqvae":
        {
            "local": "/home/ahmed/Ahmed-home/1- Projects/Research/Journal 2/code/c3jepa-wm/0_results/checkpoints/best_state_step_8_acc_-0.0057.pt",
            "new_puhti": "/scratch/project_2009050/expirements/findgoal/checkpoints/phase-1-vqvae_pretraining/job_35447333/agent_vqvae_trainer/best_state_step_8_acc_-0.0057.pt",
            "puhti": "/scratch/project_2009050/expirements/findgoal/checkpoints/vqvae_pretraining/job_default_job/agent_vqvae_trainer/best_state_step_8_acc_-0.0057.pt"
        }
    }
    if model_name not in ckp_path:
        raise ValueError(f"Unknown model name: {model_name}")
    
    for hostname, path in ckp_path[model_name].items():
        if os.path.exists(path):
            print(f"Checkpoint path found for {model_name} on hostname: {hostname} in {path}")
            return path
    
    raise FileNotFoundError(f"No checkpoint path found for {model_name} on any known hostname.")


# %% ../../nbs/06a_utils.__init__.ipynb #3995a853
def init_model(cfg: DictConfig):
    """
    Instantiates the model(s).
    Returns a single model for Stage 1, or a dictionary of 3 models for Stage 2.
    """
    stage = cfg.pipeline.stage
    model_cfg = cfg.pipeline.model

    if stage == 0 or stage == 1:
        # Stage 1: Simply instantiate and return the single VQ-VAE model
        return hydra.utils.instantiate(model_cfg)

    elif stage == 2:
        # Stage 2: Instantiate JEPA independently
        model_cfg.jepa.checkpoint_path = ""
        model_cfg.vqvae.checkpoint_path = "" 

        models = {
            "jepa": hydra.utils.instantiate(model_cfg.jepa),
        }
        # if hasattr(model_cfg.jepa, "checkpoint_path") and model_cfg.jepa.checkpoint_path:
        ckpt_path = get_ckp_path("jepa")
        model_cfg.jepa.checkpoint_path = ckpt_path
        print(f"Loading pretrained JEPA weights from {model_cfg.jepa.checkpoint_path}")

        checkpoint = torch.load(model_cfg.jepa.checkpoint_path, map_location="cpu")
        models["jepa"].load_state_dict(checkpoint["wm_model_state_dict"])
        
        # Instantiate VQ-VAE, then immediately load its pretrained weights and freeze it
        vqvae = hydra.utils.instantiate(model_cfg.vqvae)
        
        # if hasattr(model_cfg.vqvae, "checkpoint_path") and model_cfg.vqvae.checkpoint_path:
        ckpt_path = get_ckp_path("vqvae")
        model_cfg.vqvae.checkpoint_path = ckpt_path
        print(f"Loading pretrained VQ-VAE weights from {model_cfg.vqvae.checkpoint_path}")

        checkpoint = torch.load(model_cfg.vqvae.checkpoint_path, map_location="cpu")
        vqvae.load_state_dict(checkpoint["model_state_dict"])
            
        # Freeze VQ-VAE because it's only used for getting latent codebooks
        vqvae.eval()
        for param in vqvae.parameters():
            param.requires_grad = False
            
        models["vqvae"] = vqvae
        return models
    

    elif stage == 3: # Evaluation stage

        model_cfg.jepa.checkpoint_path = ""
        model_cfg.vqvae.checkpoint_path = "" 

        models = {
            "jepa": hydra.utils.instantiate(model_cfg.jepa),
        }

        # if hasattr(model_cfg.jepa, "checkpoint_path") and model_cfg.jepa.checkpoint_path:
        ckpt_path = get_ckp_path("jepa")
        model_cfg.jepa.checkpoint_path = ckpt_path
        print(f"Loading pretrained JEPA weights from {model_cfg.jepa.checkpoint_path}")

        checkpoint = torch.load(model_cfg.jepa.checkpoint_path, map_location="cpu")
        models["jepa"].load_state_dict(checkpoint["wm_model_state_dict"])
        
        # Instantiate VQ-VAE, then immediately load its pretrained weights and freeze it
        vqvae = hydra.utils.instantiate(model_cfg.vqvae)
        
        # if hasattr(model_cfg.vqvae, "checkpoint_path") and model_cfg.vqvae.checkpoint_path:
        ckpt_path = get_ckp_path("vqvae")
        model_cfg.vqvae.checkpoint_path = ckpt_path
        print(f"Loading pretrained VQ-VAE weights from {model_cfg.vqvae.checkpoint_path}")

        checkpoint = torch.load(model_cfg.vqvae.checkpoint_path, map_location="cpu")
        vqvae.load_state_dict(checkpoint["model_state_dict"]) 
            
        # Freeze VQ-VAE because it's only used for getting latent codebooks
        vqvae.eval()
        for param in vqvae.parameters():
            param.requires_grad = False
            
        models["vqvae"] = vqvae
        return models
    
    else:
        raise ValueError(f"Unknown pipeline stage: {stage}")



# %% ../../nbs/06a_utils.__init__.ipynb #4946940a
def init_trainer(cfg: DictConfig, data_module, models, device, slurm_jobid):
    """Instantiates the trainer and injects the loaded models and data."""
    # We pass models and datamodule directly into the instantiation call 
    # so the trainer receives its dependencies right away.
    return hydra.utils.instantiate(
        cfg.pipeline.trainer, 
        data_module=data_module,
        model=models, 
        device=device,
        slurm_jobid=slurm_jobid
    )


# %% ../../nbs/06a_utils.__init__.ipynb #49ffaee2
def init_evaluator(cfg: DictConfig, data_module, models, device, slurm_jobid):
    """Instantiates the evaluator and injects the loaded models and data."""
    # We pass models and datamodule directly into the instantiation call 
    # so the evaluator receives its dependencies right away.
    return hydra.utils.instantiate(
        cfg.pipeline.evaluator, 
        _recursive_=False,
        data_module=data_module,
        planner_cfg= cfg.pipeline.planner,
        model=models, 
        device=device,
        slurm_jobid=slurm_jobid
    )


# %% ../../nbs/06a_utils.__init__.ipynb #c79732a8
@torch.no_grad()
def channel(schedule, power, msg_indices, csi, device, codebook_size=256, snr_db=10.0, no_comm= False):
    """
    schedule:    (B*T, n, 1)
    power:       (B*T, n, 1)
    msg_indices: (B*T, 49)
    csi:         (B*T, n, 1) complex
    returns:     (B*T, 49) recovered indices (per neighbor averaged or selected)
    """
    if schedule is None or power is None:
        return msg_indices

    symbol_length = int(math.log2(codebook_size))  # 8 bits for k=256
    BT, msg_dim = msg_indices.shape
    n = csi.shape[1]

    # Expand message for each neighbor: (B*T, n, 49)
    msg_expanded = msg_indices.unsqueeze(1).expand(-1, n, -1)
    msg_flat = msg_expanded.reshape(BT * n, msg_dim)           # (B*T*n, 49)

    # Flatten neighbor dim for schedule/power/csi
    schedule_flat = rearrange(schedule, "b n d -> (b n) d")    # (B*T*n, 1)
    power_flat    = rearrange(power,    "b n d -> (b n) d")    # (B*T*n, 1)
    csi_flat      = rearrange(csi,      "b n d -> (b n) d")    # (B*T*n, 1) complex

    # 1. Binarize — vectorized
    bit_shifts = torch.arange(symbol_length, device=device)       # (8,)
    bits = ((msg_flat.unsqueeze(-1) >> bit_shifts) & 1).float()        # (B*T*n, 49, 8)
    bits = bits.reshape(BT * n, msg_dim * symbol_length)               # (B*T*n, 392)

    # 2. BPSK modulation: 0 → -1, 1 → +1
    modulated = 2 * bits - 1                                           # (B*T*n, 392)

    # 3. Power scaling
    modulated = modulated * torch.sqrt(power_flat)                     # (B*T*n, 392)

    # 4. Channel effect + AWGN
    snr_linear = 10 ** (snr_db / 10.0)
    noise_std = torch.sqrt(power_flat / snr_linear)                    # (B*T*n, 1)
    noise = (torch.randn_like(modulated) + 1j * torch.randn_like(modulated)) * noise_std / math.sqrt(2)
    received = modulated * csi_flat + noise    # (B*T*n, 392) complex
    # Note: using real part of csi for BPSK (real-valued modulation)

    # 5. Matched filter demodulation
    demodulated = ((received * torch.conj(csi_flat)).real > 0).float() # (B*T*n, 392)

    # 6. De-binarize — vectorized
    bit_weights = (2 ** bit_shifts).long()                             # (8,)
    recovered = (
        demodulated.reshape(BT * n, msg_dim, symbol_length).long()
        * bit_weights
    ).sum(-1)                                                           # (B*T*n, 49)

    # 7. Apply schedule: if not scheduled, receiver gets no message
    # Fall back to original indices (no information case)
    ##If schedule=1 (send): recovered = 1 * recovered + 0 * msg_flat → use the channel-degraded received message 
    # If schedule=0 (don't send): recovered = 0 * recovered + 1 * msg_flat → use original indices
    
    schedule_mask = (schedule_flat > 0.5)                   # (B*T*n, 1) bool

    # Where not scheduled, use a special null index (e.g. codebook_size as padding token)
    null_indices = torch.full_like(msg_flat, codebook_size)  # out-of-vocab index shape: (B*T*n, 49)
    if no_comm:
        recovered = null_indices
        recovered = recovered.reshape(BT, n, msg_dim)
        return recovered[:, 0, :]
    
    recovered = torch.where(schedule_mask, recovered, null_indices)

    # schedule_mask = (schedule_flat > 0.5).long()                       # (B*T*n, 1)
    # recovered = schedule_mask * recovered + (1 - schedule_mask) * msg_flat

    # 8. Reshape back: (B*T, n, 49)
    recovered = recovered.reshape(BT, n, msg_dim)

    # 9. Aggregate across neighbors
    # Simple approach: take the first neighbor (the intended one)
    # Or average if you want to combine information from multiple neighbors
    recovered = recovered[:, 0, :]                                     # (B*T, 49)

    return recovered

# %% ../../nbs/06a_utils.__init__.ipynb #ad5adc09
def compute_power_schedule(csi, snr_db, noise_power, max_power):
    """Shared by train (channel_optimal) and eval (_extract_power_and_schedule)."""
    snr_linear = 10 ** (snr_db / 10.0)
    optimal_power = snr_linear * noise_power / (csi.abs().pow(2) + 1e-8)
    schedule = (optimal_power <= max_power).float()
    return optimal_power, schedule


@torch.no_grad()
def apply_channel(msg_indices, csi, schedule, power, device, codebook_size=256,
                   noise_power=1.0, no_comm=False):
    """Shared by train (channel_optimal) and eval (channel)."""
    symbol_length = int(math.log2(codebook_size))
    BT, msg_dim = msg_indices.shape
    n = csi.shape[1]

    if no_comm:
        return torch.full((BT, msg_dim), codebook_size, dtype=msg_indices.dtype, device=device)

    msg_expanded = msg_indices.unsqueeze(1).expand(-1, n, -1)
    msg_flat = msg_expanded.reshape(BT * n, msg_dim)

    schedule_flat = rearrange(schedule, "b n d -> (b n) d")
    power_flat    = rearrange(power,    "b n d -> (b n) d")
    csi_flat      = rearrange(csi,      "b n d -> (b n) d")

    bit_shifts = torch.arange(symbol_length, device=device)
    bits = ((msg_flat.unsqueeze(-1) >> bit_shifts) & 1).float()
    bits = bits.reshape(BT * n, msg_dim * symbol_length)

    modulated = (2 * bits - 1) * torch.sqrt(power_flat)

    # FIXED: fixed noise floor, independent of transmit power
    noise_std = math.sqrt(noise_power)
    noise = (torch.randn_like(modulated) + 1j * torch.randn_like(modulated)) * noise_std / math.sqrt(2)
    received = modulated * csi_flat + noise

    demodulated = ((received * torch.conj(csi_flat)).real > 0).float()
    bit_weights = (2 ** bit_shifts).long()
    recovered = (demodulated.reshape(BT * n, msg_dim, symbol_length).long() * bit_weights).sum(-1)

    schedule_mask = (schedule_flat > 0.5)
    null_indices = torch.full_like(msg_flat, codebook_size)
    recovered = torch.where(schedule_mask, recovered, null_indices)

    recovered = recovered.reshape(BT, n, msg_dim)
    return recovered[:, 0, :]


# %% ../../nbs/06a_utils.__init__.ipynb #92f15b41
@torch.no_grad()
def channel_optimal(msg_indices, csi, device, codebook_size=256, snr_db=10.0,
                     max_power=10.0, noise_power=1.0, perfect_comm=True):
    """
    msg_indices: (B*T, 49)
    csi:         (B*T, n, 1) complex
    returns:     (B*T, 49) recovered indices
    """
    if perfect_comm:
        return msg_indices

    # --- Power control: P_required = γ · σ² / |h|²  (all quantities linear) ---
    snr_linear = 10 ** (snr_db / 10.0)                       # dB → linear, once, used everywhere
    channel_power_gain = csi.abs().pow(2)  + 1e-8                  # |h|², elementwise, shape (BT, n, 1)
    optimal_power = snr_linear * noise_power / channel_power_gain

    # Schedule: transmit (1) only if required power fits the budget
    schedule = torch.where(
        optimal_power <= max_power,
        torch.ones_like(optimal_power),
        torch.zeros_like(optimal_power),
    )

    symbol_length = int(math.log2(codebook_size))
    BT, msg_dim = msg_indices.shape
    n = csi.shape[1]

    msg_expanded = msg_indices.unsqueeze(1).expand(-1, n, -1)
    msg_flat = msg_expanded.reshape(BT * n, msg_dim)

    schedule_flat = rearrange(schedule, "b n d -> (b n) d")
    power_flat    = rearrange(optimal_power, "b n d -> (b n) d")
    csi_flat      = rearrange(csi, "b n d -> (b n) d")

    # 1. Binarize
    bit_shifts = torch.arange(symbol_length, device=device)
    bits = ((msg_flat.unsqueeze(-1) >> bit_shifts) & 1).float()
    bits = bits.reshape(BT * n, msg_dim * symbol_length)

    # 2. BPSK modulation: 0 → -1, 1 → +1
    modulated = 2 * bits - 1

    # 3. Power scaling (amplitude, so sqrt(power))
    modulated = modulated * torch.sqrt(power_flat)

    # 4. Channel effect + AWGN — fixed noise floor, independent of transmit power
    noise_std = math.sqrt(noise_power)
    noise = (torch.randn_like(modulated) + 1j * torch.randn_like(modulated)) * noise_std / math.sqrt(2)
    received = modulated * csi_flat + noise

    # 5. Matched filter demodulation
    demodulated = ((received * torch.conj(csi_flat)).real > 0).float()

    # 6. De-binarize
    bit_weights = (2 ** bit_shifts).long()
    recovered = (
        demodulated.reshape(BT * n, msg_dim, symbol_length).long() * bit_weights
    ).sum(-1)

    # 7. Apply schedule: scheduled (affordable) links use the channel-decoded message;
    #    unscheduled (unaffordable) links get a null/out-of-vocab index — no information sent.
    schedule_mask = (schedule_flat > 0.5)
    null_indices = torch.full_like(msg_flat, codebook_size)
    recovered = torch.where(schedule_mask, recovered, null_indices)

    # 8. Reshape back: (BT, n, 49)
    recovered = recovered.reshape(BT, n, msg_dim)

    # 9. Take the intended neighbor
    recovered = recovered[:, 0, :]

    return recovered

# %% ../../nbs/06a_utils.__init__.ipynb #92667030
class PhaseTransitionChecker:
    def __init__(
        self,
        plateau_patience: int = 10,      # epochs to wait for plateau
        plateau_threshold: float = 1e-3, # min relative change to not be plateau
        reward_patience: int = 5,        # epochs reward must be positive
        schedule_rate_min: float = 0.1,  # schedule rate must be above this
        schedule_rate_max: float = 0.9,  # schedule rate must be below this
    ):
        self.plateau_patience = plateau_patience
        self.plateau_threshold = plateau_threshold
        self.reward_patience = reward_patience
        self.schedule_rate_min = schedule_rate_min
        self.schedule_rate_max = schedule_rate_max

        self.loss_history = []
        self.reward_history = []
        self.schedule_rate_history = []

    def update(self, metrics: dict):
        if "val_jepa_loss" in metrics:
            self.loss_history.append(metrics["val_jepa_loss"])
        if "val_reward" in metrics:
            self.reward_history.append(metrics["val_reward"])
        if "val_schedule_rate" in metrics:
            self.schedule_rate_history.append(metrics["val_schedule_rate"])

    def _is_plateaued(self) -> bool:
        """Check if jepa loss has stopped improving"""
        if len(self.loss_history) < self.plateau_patience:
            return False  # not enough history yet

        recent = self.loss_history[-self.plateau_patience:]
        best = min(recent)
        worst = max(recent)

        # Plateau if relative change is below threshold
        relative_change = (worst - best) / (best + 1e-8)
        return relative_change < self.plateau_threshold

    def _reward_is_stable(self) -> bool:
        """Check if reward is consistently positive and not collapsing"""
        if len(self.reward_history) < self.reward_patience:
            return False

        recent_rewards = self.reward_history[-self.reward_patience:]
        return all(r > 0 for r in recent_rewards)

    def _schedule_is_healthy(self) -> bool:
        """Check schedule rate is neither always 0 nor always 1"""
        if len(self.schedule_rate_history) < self.reward_patience:
            return False

        recent_rates = self.schedule_rate_history[-self.reward_patience:]
        avg_rate = sum(recent_rates) / len(recent_rates)
        return self.schedule_rate_min < avg_rate < self.schedule_rate_max

    def should_transition_to_phase2(self) -> bool:
        plateaued = self._is_plateaued()
        if plateaued:
            print(
                f"Phase 1→2 transition: jepa_loss plateaued "
                f"(last {self.plateau_patience} epochs: "
                f"{[f'{v:.4f}' for v in self.loss_history[-self.plateau_patience:]]})"
            )
        return plateaued

    def should_transition_to_phase3(self) -> bool:
        reward_ok   = self._reward_is_stable()
        schedule_ok = self._schedule_is_healthy()

        if reward_ok and schedule_ok:
            print(
                f"Phase 2→3 transition: "
                f"reward stable (last {self.reward_patience}: "
                f"{[f'{v:.4f}' for v in self.reward_history[-self.reward_patience:]]}) "
                f"schedule rate healthy "
                f"(last {self.reward_patience}: "
                f"{[f'{v:.4f}' for v in self.schedule_rate_history[-self.reward_patience:]]})"
            )
        elif not reward_ok:
            print(f"Phase 2→3 blocked: reward not stable yet "
                  f"(recent: {[f'{v:.4f}' for v in self.reward_history[-self.reward_patience:]]})")
        elif not schedule_ok:
            print(f"Phase 2→3 blocked: schedule rate unhealthy "
                  f"(recent avg: {sum(self.schedule_rate_history[-self.reward_patience:]) / self.reward_patience:.4f}, "
                  f"need {self.schedule_rate_min:.1f}–{self.schedule_rate_max:.1f})")

        return reward_ok and schedule_ok

    def reset(self):
        """Call when transitioning phases to start fresh history"""
        self.loss_history = []
        self.reward_history = []
        self.schedule_rate_history = []
