# configs/datamodule/vqvae_data.yaml
_target_: c3jepa_wm.data.data_module.VQDataModule # Full python import path to your datamodule class

batch_size: 128
num_workers: 0
img_size: ${pipeline.model.img_size} # Grabs from pipeline config, which can be overridden by config.yaml
# Optional: Add any path configurations your dataset needs
# data_dir: "data/images/"