# configs/train/pipeline/wm_train.yaml
defaults:
  - /datamodule: jepa_data
  - /model@model.jepa: control_jepa
  - _self_

stage: 0

# Define Stage 0 specific hyperparameters here
wm_lr: 1e-4
max_epochs: 100
num_workers: 6
train_split: 0.9
seed: 3072
img_size: 224
embed_dim: 192
msg_embedding_dim: 256
num_embeddings: 256
history_size: 3


trainer:
  _target_: c3jepa_wm.trainers.world_model.WMTrainer
  epochs: ${pipeline.max_epochs} # Automatically grabs 100
  wm_lr: ${pipeline.wm_lr}             # Automatically grabs 1e-4
  history_size: ${pipeline.history_size} # Automatically grabs 3
  num_preds: 1
  lambda_sigreg: 0.1
  early_stop_patience: 10

optimizer:
  _target_: torch.optim.AdamW
  lr: ${pipeline.wm_lr}
  weight_decay: 1e-3


loss:
  sigreg:
    weight: 0.09
    kwargs:
      knots: 17
      num_proj: 1024



  