# configs/datamodule/jepa_data.yaml
_target_: c3jepa_wm.data.data_module.WMDataModule # Full python import path to your datamodule class

batch_size: 1 # 128
num_workers: 0
history_size: ${pipeline.history_size} # Automatically grabs 3 from pipeline config!
img_size: ${pipeline.img_size} # Grabs from pipeline config, which can be overridden by config.yaml
