"""A LEWM-based architecture for learning representations of subseqt observations from current ones."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02c_models.lewm.ipynb.

# %% auto #0
__all__ = []

# %% ../../nbs/02c_models.lewm.ipynb #1843b6b8
import torch
from torch import nn
from torch.nn import functional as F

