"""A LEWM-based architecture for learning representations of subseqt observations from current ones."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02c_models.jepa.ipynb.

# %% auto #0
__all__ = ['modulate', 'csi_to_features', 'SIGReg', 'DiscreteActionEncoder', 'FeedForward', 'Attention',
           'MessageConditionedBlock', 'ConditionalBlock', 'Block', 'Transformer', 'Embedder', 'MLP', 'ARPredictor',
           'detach_clone', 'JEPA']

# %% ../../nbs/02c_models.jepa.ipynb #2392243b
import torch
from torch import nn
from torch.nn import functional as F
from einops import rearrange


# %% ../../nbs/02c_models.jepa.ipynb #776969f1
def modulate(x, shift, scale):
    """AdaLN-zero modulation"""
    return x * (1 + scale) + shift

def csi_to_features(csi: torch.Tensor, eps: float = 1e-6) -> torch.Tensor:
    """
    csi: (B, T) complex tensor, single-antenna channel coefficient
    returns: (B, T, 3) real feature tensor [log|h|, sin(angle), cos(angle)]
    """
    mag = csi.abs()
    log_mag = torch.log(mag + eps)
    angle = csi.angle()
    return torch.stack([log_mag, angle.sin(), angle.cos()], dim=-1)


# %% ../../nbs/02c_models.jepa.ipynb #3965d6fd
class SIGReg(torch.nn.Module):
    """Sketch Isotropic Gaussian Regularizer (single-GPU!)"""

    def __init__(self, knots=17, num_proj=1024):
        super().__init__()
        self.num_proj = num_proj
        t = torch.linspace(0, 3, knots, dtype=torch.float32)
        dt = 3 / (knots - 1)
        weights = torch.full((knots,), 2 * dt, dtype=torch.float32)
        weights[[0, -1]] = dt
        window = torch.exp(-t.square() / 2.0)
        self.register_buffer("t", t)
        self.register_buffer("phi", window)
        self.register_buffer("weights", weights * window)

    def forward(self, proj):
        """
        proj: (T, B, D)
        """
        # sample random projections
        A = torch.randn(proj.size(-1), self.num_proj, device=proj.device)
        A = A.div_(A.norm(p=2, dim=0))
        # compute the epps-pulley statistic
        x_t = (proj @ A).unsqueeze(-1) * self.t
        err = (x_t.cos().mean(-3) - self.phi).square() + x_t.sin().mean(-3).square()
        statistic = (err @ self.weights) * proj.size(-2)
        return statistic.mean() # average over projections and time
    

# %% ../../nbs/02c_models.jepa.ipynb #77dc6c7a
class DiscreteActionEncoder(nn.Module):
    def __init__(self, num_actions, action_emb_dim):
        super().__init__()
        self.embedding = nn.Embedding(num_actions, action_emb_dim)
    
    def forward(self, action):
        """
        action: (B, T) integer indices
        returns: (B, T, action_emb_dim)
        """
        return self.embedding(action)
    

# %% ../../nbs/02c_models.jepa.ipynb #f93f8539
class FeedForward(nn.Module):
    """FeedForward network used in Transformers"""

    def __init__(self, dim, hidden_dim, dropout=0.0):
        super().__init__()
        self.net = nn.Sequential(
            nn.LayerNorm(dim),
            nn.Linear(dim, hidden_dim),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim, dim),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)


# %% ../../nbs/02c_models.jepa.ipynb #295b02b3
class Attention(nn.Module):
    """Scaled dot-product attention with causal masking"""

    def __init__(self, dim, heads=8, dim_head=64, dropout=0.0):
        super().__init__()
        inner_dim = dim_head * heads
        project_out = not (heads == 1 and dim_head == dim)
        self.heads = heads
        self.scale = dim_head**-0.5
        self.dropout = dropout
        self.norm = nn.LayerNorm(dim)
        self.attend = nn.Softmax(dim=-1)
        self.to_qkv = nn.Linear(dim, inner_dim * 3, bias=False)
        self.to_out = (
            nn.Sequential(nn.Linear(inner_dim, dim), nn.Dropout(dropout))
            if project_out
            else nn.Identity()
        )

    def forward(self, x, causal=True):
        """
        x : (B, T, D)
        """
        x = self.norm(x)
        drop = self.dropout if self.training else 0.0
        qkv = self.to_qkv(x).chunk(3, dim=-1)  # q, k, v: (B, heads, T, dim_head)
        q, k, v = (rearrange(t, "b t (h d) -> b h t d", h=self.heads) for t in qkv)
        out = F.scaled_dot_product_attention(q, k, v, dropout_p=drop, is_causal=causal)
        out = rearrange(out, "b h t d -> b t (h d)")
        return self.to_out(out)



# %% ../../nbs/02c_models.jepa.ipynb #4c2495ef
class MessageConditionedBlock(nn.Module):
    def __init__(self, dim, heads, dim_head, mlp_dim, dropout=0.0, csi_feat_dim=3):
        super().__init__()
        self.attn = Attention(dim, heads=heads, dim_head=dim_head, dropout=dropout)
        self.mlp = FeedForward(dim, mlp_dim, dropout=dropout)
        self.norm1 = nn.LayerNorm(dim, elementwise_affine=False, eps=1e-6)
        self.norm2 = nn.LayerNorm(dim, elementwise_affine=False, eps=1e-6)
        self.adaLN_modulation = nn.Sequential(
            nn.SiLU(), nn.Linear(dim, 6 * dim, bias=True)
        )
        nn.init.constant_(self.adaLN_modulation[-1].weight, 0)
        nn.init.constant_(self.adaLN_modulation[-1].bias, 0)

        self.cross_attn = nn.MultiheadAttention(
            embed_dim=dim, num_heads=heads, batch_first=True, dropout=dropout
        )
        self.cross_norm = nn.LayerNorm(dim)

        # csi_feat_dim = width of the *preprocessed real* CSI features (e.g. 3 for [log|h|, sin, cos])
        self.csi_proj = nn.Sequential(
            nn.Linear(csi_feat_dim, dim), nn.SiLU(), nn.Linear(dim, dim)
        )

        self.msg_gate = nn.Sequential(
            nn.Linear(dim * 2, 1),
            nn.Sigmoid()
        )

    def forward(self, x, c, msg_tokens=None, csi_feat=None, return_attention=False):
        shift_msa, scale_msa, gate_msa, shift_mlp, scale_mlp, gate_mlp = (
            self.adaLN_modulation(c).chunk(6, dim=-1)
        )
        x = x + gate_msa * self.attn(modulate(self.norm1(x), shift_msa, scale_msa))

        attn_weights, gate = None, None
        if msg_tokens is not None:
            B, T, N, D = msg_tokens.shape
            msg_seq = msg_tokens.reshape(B, T * N, D)

            mask = torch.ones(T, T * N, dtype=torch.bool, device=x.device)
            for t in range(T):
                mask[t, :(t + 1) * N] = False

            msg_attended, attn_weights = self.cross_attn(
                query=self.cross_norm(x),
                key=msg_seq,
                value=msg_seq,
                attn_mask=mask,
                need_weights=True
            )

            if csi_feat is not None:
                csi_emb = self.csi_proj(csi_feat)      # (B, T, D), csi_feat already real-valued
            else:
                csi_emb = torch.zeros_like(x)

            gate = self.msg_gate(torch.cat([x, csi_emb], dim=-1))
            x = x + gate * msg_attended

        x = x + gate_mlp * self.mlp(modulate(self.norm2(x), shift_mlp, scale_mlp))

        if return_attention:
            return x, attn_weights, gate
        return x
    

# %% ../../nbs/02c_models.jepa.ipynb #a7025e2d
class ConditionalBlock(nn.Module):
    """Transformer block with AdaLN-zero conditioning"""

    def __init__(self, dim, heads, dim_head, mlp_dim, dropout=0.0):
        super().__init__()

        self.attn = Attention(dim, heads=heads, dim_head=dim_head, dropout=dropout)
        self.mlp = FeedForward(dim, mlp_dim, dropout=dropout)
        self.norm1 = nn.LayerNorm(dim, elementwise_affine=False, eps=1e-6)
        self.norm2 = nn.LayerNorm(dim, elementwise_affine=False, eps=1e-6)
        self.adaLN_modulation = nn.Sequential(
            nn.SiLU(), nn.Linear(dim, 6 * dim, bias=True)
        )

        nn.init.constant_(self.adaLN_modulation[-1].weight, 0)
        nn.init.constant_(self.adaLN_modulation[-1].bias, 0)

    def forward(self, x, c):
        shift_msa, scale_msa, gate_msa, shift_mlp, scale_mlp, gate_mlp = (
            self.adaLN_modulation(c).chunk(6, dim=-1)
        )
        x = x + gate_msa * self.attn(modulate(self.norm1(x), shift_msa, scale_msa))
        x = x + gate_mlp * self.mlp(modulate(self.norm2(x), shift_mlp, scale_mlp))
        return x



# %% ../../nbs/02c_models.jepa.ipynb #58e953bf
class Block(nn.Module):
    """Standard Transformer block"""

    def __init__(self, dim, heads, dim_head, mlp_dim, dropout=0.0):
        super().__init__()

        self.attn = Attention(dim, heads=heads, dim_head=dim_head, dropout=dropout)
        self.mlp = FeedForward(dim, mlp_dim, dropout=dropout)
        self.norm1 = nn.LayerNorm(dim, elementwise_affine=False, eps=1e-6)
        self.norm2 = nn.LayerNorm(dim, elementwise_affine=False, eps=1e-6)

    def forward(self, x):
        x = x + self.attn(self.norm1(x))
        x = x + self.mlp(self.norm2(x))
        return x



# %% ../../nbs/02c_models.jepa.ipynb #8f846bd2
class Transformer(nn.Module):
    """Standard Transformer with support for AdaLN-zero blocks"""

    def __init__(
        self,
        input_dim,
        hidden_dim,
        output_dim,
        depth,
        heads,
        dim_head,
        mlp_dim,
        dropout=0.0,
        block_class=Block,
    ):
        super().__init__()
        self.norm = nn.LayerNorm(hidden_dim)
        self.layers = nn.ModuleList([])

        self.input_proj = (
            nn.Linear(input_dim, hidden_dim)
            if input_dim != hidden_dim
            else nn.Identity()
        )

        self.cond_proj = (
            nn.Linear(input_dim, hidden_dim)
            if input_dim != hidden_dim
            else nn.Identity()
        )

        self.output_proj = (
            nn.Linear(hidden_dim, output_dim)
            if hidden_dim != output_dim
            else nn.Identity()
        )

        for _ in range(depth):
            self.layers.append(
                block_class(hidden_dim, heads, dim_head, mlp_dim, dropout)
            )

    def forward(self, x, c=None, msg_tokens=None, csi_feat=None, return_attention=False):

        if hasattr(self, "input_proj"):
            x = self.input_proj(x)
        if c is not None and hasattr(self, "cond_proj"):
            c = self.cond_proj(c)

        all_attn_weights = []
        all_gates = []

        for block in self.layers:
            if isinstance(block, MessageConditionedBlock):
                if return_attention:
                    x, attn, gate = block(x, c, msg_tokens=msg_tokens, return_attention=True)
                    all_attn_weights.append(attn)
                    all_gates.append(gate)
                else:
                    x = block(x, c, msg_tokens=msg_tokens, csi_feat=csi_feat, return_attention=False)
            elif isinstance(block, ConditionalBlock):
                x = block(x, c)
            else:
                x = block(x)

        x = self.norm(x)
        if hasattr(self, "output_proj"):
            x = self.output_proj(x)

        if return_attention:
            return x, all_attn_weights, all_gates
        return x


# %% ../../nbs/02c_models.jepa.ipynb #cb6aa01e
class Embedder(nn.Module):
    def __init__(
        self,
        input_dim=10,
        smoothed_dim=10,
        emb_dim=10,
        mlp_scale=4,
    ):
        super().__init__()
        self.patch_embed = nn.Conv1d(input_dim, smoothed_dim, kernel_size=1, stride=1)
        self.embed = nn.Sequential(
            nn.Linear(smoothed_dim, mlp_scale * emb_dim),
            nn.SiLU(),
            nn.Linear(mlp_scale * emb_dim, emb_dim),
        )

    def forward(self, x):
        """
        x: (B, T, D)
        """
        x = x.float()
        x = x.permute(0, 2, 1)
        x = self.patch_embed(x)
        x = x.permute(0, 2, 1)
        x = self.embed(x)
        return x



# %% ../../nbs/02c_models.jepa.ipynb #0bf2992b
class MLP(nn.Module):
    """Simple MLP with optional normalization and activation"""

    def __init__(
        self,
        input_dim,
        hidden_dim,
        output_dim=None,
        norm_fn=nn.LayerNorm,
        act_fn=nn.GELU,
    ):
        super().__init__()
        norm_fn = norm_fn(hidden_dim) if norm_fn is not None else nn.Identity()
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            norm_fn,
            act_fn(),
            nn.Linear(hidden_dim, output_dim or input_dim),
        )

    def forward(self, x):
        """
        x: (B*T, D)
        """
        return self.net(x)



# %% ../../nbs/02c_models.jepa.ipynb #1924be2e
class ARPredictor(nn.Module):
    def __init__(
        self,
        *,
        num_frames,
        depth,
        heads,
        mlp_dim,
        input_dim,
        hidden_dim,
        output_dim=None,
        dim_head=64,
        dropout=0.0,
        emb_dropout=0.0,
        msg_embedding_dim=256,   # VQ-VAE embedding_dim
        num_embeddings=256,      # VQ-VAE codebook size
        num_msg_tokens=49,       # spatial grid size (7x7), no longer hardcoded
    ):
        super().__init__()
        self.pos_embedding = nn.Parameter(torch.randn(1, num_frames, input_dim))
        self.dropout = nn.Dropout(emb_dropout)

        self.msg_proj = (
            nn.Linear(msg_embedding_dim, hidden_dim)
            if msg_embedding_dim != hidden_dim
            else nn.Identity()
        )

        self.msg_token_embedding = nn.Embedding(
            num_embeddings + 1, msg_embedding_dim, padding_idx=num_embeddings
        )

        # NEW: positional embeddings for message tokens
        self.num_msg_tokens = num_msg_tokens
        self.msg_pos_spatial = nn.Parameter(torch.randn(1, 1, num_msg_tokens, hidden_dim) * 0.02)
        self.msg_pos_temporal = nn.Parameter(torch.randn(1, num_frames, 1, hidden_dim) * 0.02)

        self.transformer = Transformer(
            input_dim,
            hidden_dim,
            output_dim or input_dim,
            depth,
            heads,
            dim_head,
            mlp_dim,
            dropout,
            block_class=MessageConditionedBlock,
        )

    def forward(self, x, c, msg_indices=None, csi=None, return_attention=False):
        """
        x:           (B, T, D)    — state embeddings
        c:           (B, T, D)    — action embeddings
        msg_indices: (B, T, 49)   — VQ token indices from sender, optional
        csi:         (B, T)       — complex tensor, single-antenna channel coefficient — raw from Sionna
        """
        T = x.size(1)
        x = x + self.pos_embedding[:, :T]
        x = self.dropout(x)

        m = None
        if msg_indices is not None:
            msg_indices = rearrange(msg_indices, "b t n -> (b t) n")
            m = self.msg_token_embedding(msg_indices)   # (B*T, 49, msg_embedding_dim)
            m = self.msg_proj(m)               # (B*T, 49, D)
            m = rearrange(m, "(b t) n d -> b t n d", b=x.size(0), t=T)

            # NEW: add spatial + temporal position embeddings
            m = m + self.msg_pos_spatial + self.msg_pos_temporal[:, :T]

        if return_attention:
            x, attn_weights, gates = self.transformer(
                x, c, msg_tokens=m, return_attention=True
            )
            return x, attn_weights, gates
        
        csi_feat = csi_to_features(csi) if csi is not None else None
        x = self.transformer(x, c, msg_tokens=m, csi_feat=csi_feat)
        return x
    

# %% ../../nbs/02c_models.jepa.ipynb #a204719d
"""JEPA Implementation"""

def detach_clone(v):
    return v.detach().clone() if torch.is_tensor(v) else v

class JEPA(nn.Module):

    def __init__(
        self,
        encoder,
        predictor,
        action_encoder,
        projector=None,
        pred_proj=None,
        **kwargs
    ):
        super().__init__()

        self.encoder = encoder
        self.predictor = predictor
        self.action_encoder = action_encoder
        self.projector = projector or nn.Identity()
        self.pred_proj = pred_proj or nn.Identity()
        self.sigreg = SIGReg(knots=17, num_proj=1024)

    def encode(self, info):
        """Encode observations and actions into embeddings.
        info: dict with pixels and action keys
        """
        pixels = info['pixels']
        b = pixels.size(0)
        pixels = rearrange(pixels, "b t ... -> (b t) ...") # flatten for encoding
        output = self.encoder(pixels, interpolate_pos_encoding=True)
        pixels_emb = output.last_hidden_state[:, 0]  # cls token
        emb = self.projector(pixels_emb)
        info["emb"] = rearrange(emb, "(b t) d -> b t d", b=b)

        if "action" in info:
            info["act_emb"] = self.action_encoder(info["action"])#.to(device))

        return info

    def predict(self, emb, act_emb, msg_indices=None, csi=None):
        """Predict next state embedding
        emb: (B, T, D) 
        act_emb: (B, T, A_emb)
        msg_indices: (B, T, 49)
        csi: (B, T) complex tensor, single-antenna channel coefficient, optional
        """
        preds = self.predictor(emb, act_emb, msg_indices=msg_indices, csi=csi)
        preds = self.pred_proj(rearrange(preds, "b t d -> (b t) d"))
        preds = rearrange(preds, "(b t) d -> b t d", b=emb.size(0))
        return preds
    

    def loss_fn(self, output, pred_emb, target_emb, emb, lambd):
        output["pred_loss"] = (pred_emb - target_emb).pow(2).mean()
        output["sigreg_loss"]= self.sigreg(emb.transpose(0, 1))
        output["jepa_loss"] = output["pred_loss"] + lambd * output["sigreg_loss"] 
        return output

    ####################
    ## Inference only ##
    ####################

    
    def rollout(self, info, action_sequence, history_size: int = 3, num_embeddings=256):
        """Rollout the model given an initial info dict and action sequence.
        pixels: (B, S, T, C, H, W)
        action_sequence: (B, S, T, action_dim)
        msg_indices: (B, S, 1, 49) VQ token indices from sender, optional
        csi: (B, S, 1) complex tensor, single-antenna channel coefficient, optional
        - S is the number of action plan samples
        - T is the time horizon
        """

        assert "pixels" in info, "pixels not in info_dict"
        H = info["pixels"].size(2)
        B, S, T = action_sequence.shape[:3]
        act_0, act_future = torch.split(action_sequence, [H, T - H], dim=2)
        info["action"] = act_0
        n_steps = T - H

        _init = {k: v[:, 0] for k, v in info.items() if torch.is_tensor(v)}
        _init = self.encode(_init)
        emb = info["emb"] = _init["emb"].unsqueeze(1).expand(B, S, -1, -1)
        _init = {k: detach_clone(v) for k, v in _init.items()}

        emb = rearrange(emb, "b s ... -> (b s) ...").clone()
        act = rearrange(act_0, "b s ... -> (b s) ...")
        act_future = rearrange(act_future, "b s ... -> (b s) ...")

        HS = history_size
        for t in range(n_steps):
            if t > 0:
                step_msg_indices = None
                step_csi = None                    # NEW: no channel reading for imagined steps
            else:
                step_msg_indices = info.get("msg_indices", None)
                step_csi = info.get("csi", None)    # NEW

                if step_msg_indices is not None:
                    step_msg_indices = rearrange(step_msg_indices, "b s o n -> (b s) o n")

                    pad_steps = HS - step_msg_indices.size(1)
                    pad = torch.full(
                        (step_msg_indices.size(0), pad_steps, step_msg_indices.size(2)),
                        fill_value=num_embeddings,
                        dtype=step_msg_indices.dtype,
                        device=step_msg_indices.device,
                    )
                    step_msg_indices = torch.cat([pad, step_msg_indices], dim=1)  # (BS, HS, 49)

                if step_csi is not None:                                          # NEW block
                    step_csi = rearrange(step_csi.squeeze(-1), "b s o -> (b s) o")
                    pad_steps = HS - step_csi.size(1)
                    # zero complex value = no channel reading; note this naturally maps to a very
                    # negative log-magnitude in csi_to_features, i.e. "worst-case" channel, which
                    # is a sensible default for "no real message was present at this history step"
                    csi_pad = torch.zeros(
                        step_csi.size(0), pad_steps,
                        dtype=step_csi.dtype, device=step_csi.device,
                    )
                    step_csi = torch.cat([csi_pad, step_csi], dim=1)  # (BS, HS)

            act_emb = self.action_encoder(act)
            emb_trunc = emb[:, -HS:]
            act_trunc = act_emb[:, -HS:]
            pred_emb = self.predict(emb_trunc, act_trunc, step_msg_indices, step_csi)[:, -1:]  # NEW: pass csi
            emb = torch.cat([emb, pred_emb], dim=1)

            next_act = act_future[:, t : t + 1]
            act = torch.cat([act, next_act], dim=1)

        act_emb = self.action_encoder(act)
        emb_trunc = emb[:, -HS:]
        act_trunc = act_emb[:, -HS:]
        pred_emb = self.predict(emb_trunc, act_trunc)[:, -1:]  # no msg_indices, no csi — correct, matches existing behavior
        emb = torch.cat([emb, pred_emb], dim=1)

        pred_rollout = rearrange(emb, "(b s) ... -> b s ...", b=B, s=S)
        info["predicted_emb"] = pred_rollout

        return info


    def criterion(self, info_dict: dict):
        """Compute the cost between predicted embeddings and goal embeddings."""
        pred_emb = info_dict["predicted_emb"]  # (B,S, T-1, dim)
        goal_emb = info_dict["goal_emb"]  # (B, S, T, dim)

        goal_emb = goal_emb[..., -1:, :].expand_as(pred_emb)

        # return last-step cost per action candidate
        cost = F.mse_loss(
            pred_emb[..., -1:, :],
            goal_emb[..., -1:, :].detach(),
            reduction="none",
        ).sum(dim=tuple(range(2, pred_emb.ndim)))  # (B, S)

        return cost

    def get_cost(self, info_dict: dict, action_candidates: torch.Tensor):
        """ Compute the cost of action candidates given an info dict with goal and initial state."""

        assert "goal" in info_dict, "goal not in info_dict"

        device = next(self.parameters()).device
        for k in list(info_dict.keys()):
            if torch.is_tensor(info_dict[k]):
                info_dict[k] = info_dict[k].to(device)

        goal = {k: v[:, :1] for k, v in info_dict.items() if torch.is_tensor(v)}
        goal["pixels"] = goal["goal"]

        for k in info_dict:
            if k.startswith("goal_"):
                goal[k[len("goal_") :]] = goal.pop(k)

        goal.pop("action")
        goal = self.encode(goal)
        info_dict["goal_emb"] = goal["emb"].unsqueeze(2)  # (B, S=1, T=1, D) — ready to broadcast in criterion
        info_dict = self.rollout(info_dict, action_candidates)

        cost = self.criterion(info_dict)
        
        return cost
    
