"""A semantic message encoder implemented as VQ-VAE, which encodes the message into a discrete latent space."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02a_models.msg_net.ipynb.

# %% auto #0
__all__ = ['Tensor', 'BaseVAE', 'VectorQuantizer', 'ResidualLayer', 'VQVAE']

# %% ../../nbs/02a_models.msg_net.ipynb #92507ff1
import torch
from torch import nn
from torch.nn import functional as F


# %% ../../nbs/02a_models.msg_net.ipynb #4a980c8d
from typing import List, Callable, Union, Any, TypeVar, Tuple

Tensor = TypeVar('torch.tensor')

# %% ../../nbs/02a_models.msg_net.ipynb #8441ba46
from torch import nn
from abc import abstractmethod

class BaseVAE(nn.Module):
    
    def __init__(self) -> None:
        super(BaseVAE, self).__init__()

    def encode(self, input: Tensor) -> List[Tensor]:
        raise NotImplementedError

    def decode(self, input: Tensor) -> Any:
        raise NotImplementedError

    def sample(self, batch_size:int, current_device: int, **kwargs) -> Tensor:
        raise NotImplementedError

    def generate(self, x: Tensor, **kwargs) -> Tensor:
        raise NotImplementedError

    @abstractmethod
    def forward(self, *inputs: Tensor) -> Tensor:
        pass

    @abstractmethod
    def loss_function(self, *inputs: Any, **kwargs) -> Tensor:
        pass

# %% ../../nbs/02a_models.msg_net.ipynb #6e3228e9
class VectorQuantizer(nn.Module):
    def __init__(self, num_embeddings, embedding_dim, beta=0.25, decay=0.99, eps=1e-5):
        super().__init__()
        self.K = num_embeddings
        self.D = embedding_dim
        self.beta = beta
        self.decay = decay
        self.eps = eps

        embedding = torch.randn(num_embeddings, embedding_dim)
        self.register_buffer('embedding', embedding)
        self.register_buffer('cluster_size', torch.zeros(num_embeddings))
        self.register_buffer('ema_embed', embedding.clone())

    def forward(self, latents):
        latents = latents.permute(0, 2, 3, 1).contiguous()
        latents_shape = latents.shape
        flat_latents = latents.view(-1, self.D)

        dist = (torch.sum(flat_latents ** 2, dim=1, keepdim=True)
                + torch.sum(self.embedding ** 2, dim=1)
                - 2 * torch.matmul(flat_latents, self.embedding.t()))

        encoding_inds = torch.argmin(dist, dim=1).unsqueeze(1)
        encoding_one_hot = torch.zeros(encoding_inds.size(0), self.K, device=latents.device)
        encoding_one_hot.scatter_(1, encoding_inds, 1)

        avg_probs = encoding_one_hot.mean(0).detach()  # [K] — average usage of each code
        perplexity = torch.exp(-torch.sum(avg_probs * torch.log(avg_probs + 1e-10)))

        quantized_latents = torch.matmul(encoding_one_hot, self.embedding)
        quantized_latents = quantized_latents.view(latents_shape)

        if self.training:
            # EMA update — happens outside the gradient graph
            self.cluster_size.mul_(self.decay).add_(
                encoding_one_hot.sum(0).detach(), alpha=1 - self.decay
            )
            dw = torch.matmul(encoding_one_hot.t(), flat_latents.detach())
            self.ema_embed.mul_(self.decay).add_(dw, alpha=1 - self.decay)

            # Laplace smoothing to avoid dead codes
            n = self.cluster_size.sum()
            smoothed = (self.cluster_size + self.eps) / (n + self.K * self.eps) * n
            # self.embedding = self.ema_embed / smoothed.unsqueeze(1)
            self.embedding.copy_(self.ema_embed / smoothed.unsqueeze(1))

        # Only commitment loss — no embedding_loss needed
        vq_loss = self.beta * F.mse_loss(quantized_latents.detach(), latents)

        quantized_latents = latents + (quantized_latents - latents).detach()
        return quantized_latents.permute(0, 3, 1, 2).contiguous(), vq_loss, perplexity
    

# %% ../../nbs/02a_models.msg_net.ipynb #acc29661
class ResidualLayer(nn.Module):

    def __init__(self,
                 in_channels: int,
                 out_channels: int):
        super(ResidualLayer, self).__init__()
        self.resblock = nn.Sequential(nn.Conv2d(in_channels, out_channels,
                                                kernel_size=3, padding=1, bias=False),
                                      nn.ReLU(True),
                                      nn.Conv2d(out_channels, out_channels,
                                                kernel_size=1, bias=False))

    def forward(self, input: Tensor) -> Tensor:
        return input + self.resblock(input)



# %% ../../nbs/02a_models.msg_net.ipynb #229dad53
class VQVAE(BaseVAE):

    def __init__(self,
                 in_channels: int,
                 embedding_dim: int,
                 num_embeddings: int,
                 hidden_dims: List = [64, 128, 256, 512, 512], # Added an extra layer (e.g., 512) to handle the smooth 28 -> 14 -> 7 downsampling
                 beta: float = 0.25,
                 img_size: int = 224, # Updated default to your target size
                 num_residual_layers: int = 3,
                 **kwargs) -> None:
        super(VQVAE, self).__init__()

        self.embedding_dim = embedding_dim
        self.num_embeddings = num_embeddings
        self.img_size = img_size
        self.beta = beta
        self.num_residual_layers = num_residual_layers

        # =====================================================================
        # BUILD ENCODER
        # =====================================================================
        modules = []

        # Smoothly handles: 224 -> 112 -> 56 -> 28 -> 14 -> 7
        for h_dim in hidden_dims:
            modules.append(
                nn.Sequential(
                    nn.Conv2d(in_channels, out_channels=h_dim,
                              kernel_size=4, stride=2, padding=1),
                    nn.LeakyReLU())
            )
            in_channels = h_dim

        # 3x3 conv at the deepest resolution (7x7)
        modules.append(
            nn.Sequential(
                nn.Conv2d(in_channels, in_channels,
                          kernel_size=3, stride=1, padding=1),
                nn.LeakyReLU())
        )

        # Residual layers at 7x7 (Better for learning abstract representations)
        for _ in range(self.num_residual_layers):
            modules.append(ResidualLayer(in_channels, in_channels))
        modules.append(nn.LeakyReLU())

        # Clean 1x1 projection to embedding dimension (7x7xembedding_dim)
        modules.append(
            nn.Sequential(
                nn.Conv2d(in_channels, embedding_dim, kernel_size=1, stride=1),
                nn.LeakyReLU())
        )

        self.encoder = nn.Sequential(*modules)
        
        # Vector Quantizer
        self.vq_layer = VectorQuantizer(num_embeddings, embedding_dim, self.beta)

        # =====================================================================
        # BUILD DECODER
        # =====================================================================
        modules = []

        # Project from embedding_dim back to the deep hidden dimension
        modules.append(
            nn.Sequential(
                nn.Conv2d(embedding_dim, hidden_dims[-1],
                          kernel_size=3, stride=1, padding=1),
                nn.LeakyReLU())
        )

        # Residual layers at 7x7
        for _ in range(self.num_residual_layers):
            modules.append(ResidualLayer(hidden_dims[-1], hidden_dims[-1]))
        modules.append(nn.LeakyReLU())

        # Upsampling blocks: 7 -> 14 -> 28 -> 56 -> 112
        # Loops safely through all inverted dims except the last one
        hidden_dims_reversed = hidden_dims[::-1]
        for i in range(len(hidden_dims_reversed) - 1):
            modules.append(
                nn.Sequential(
                    nn.ConvTranspose2d(hidden_dims_reversed[i], hidden_dims_reversed[i + 1],
                                       kernel_size=4, stride=2, padding=1),
                    nn.LeakyReLU())
            )

        # Final upsample to 3 channels: 112 -> 224
        modules.append(
            nn.Sequential(
                nn.ConvTranspose2d(hidden_dims_reversed[-1], out_channels=3,
                                   kernel_size=4, stride=2, padding=1),
                nn.Tanh())
        )

        self.decoder = nn.Sequential(*modules)



    def encode(self, input: Tensor) -> List[Tensor]:
        """
        Encodes the input by passing through the encoder network
        and returns the latent codes.
        :param input: (Tensor) Input tensor to encoder [N x C x H x W]
        :return: (Tensor) List of latent codes
        """
        result = self.encoder(input)
        return [result]

    def decode(self, z: Tensor) -> Tensor:
        """
        Maps the given latent codes
        onto the image space.
        :param z: (Tensor) [B x D x H x W]
        :return: (Tensor) [B x C x H x W]
        """

        result = self.decoder(z)
        return result

    def forward(self, input: Tensor, **kwargs) -> List[Tensor]:
        encoding = self.encode(input)[0]
        quantized_inputs, vq_loss, perplexity = self.vq_layer(encoding)
        
        return [self.decode(quantized_inputs), input, vq_loss, perplexity]

    def loss_function(self,
                      *args,
                      **kwargs) -> dict:
        """
        :param args:
        :param kwargs:
        :return:
        """
        recons = args[0]
        input = args[1]
        vq_loss = args[2]
        perplexity = args[3]
        # recons_loss = F.l1_loss(recons, input)

        # Weight non-black pixels more heavily
        pixel_weights = (input > -0.9).float() * 9.0 + 1.0  # 10x weight on non-black
        recons_loss = (F.l1_loss(recons, input, reduction='none') * pixel_weights).mean()
        

        loss = recons_loss + vq_loss
        return {'loss': loss,
                'Reconstruction_Loss': recons_loss,
                'VQ_Loss': vq_loss,
                'Perplexity': perplexity}

    def sample(self,
               num_samples: int,
               current_device: Union[int, str], **kwargs) -> Tensor:
        raise Warning('VQVAE sampler is not implemented.')

    def generate(self, x: Tensor, **kwargs) -> Tensor:
        """
        Given an input image x, returns the reconstructed image
        :param x: (Tensor) [B x C x H x W]
        :return: (Tensor) [B x C x H x W]
        """

        return self.forward(x)[0]
    

    def get_message_indices(self, obs):
        """Returns 49 discrete token indices per observation (one per grid cell)"""
        encoding = self.encode(obs)[0]  # [B, D, 7, 7]
        
        # No pooling needed — encoder already outputs 7x7
        latents = encoding.permute(0, 2, 3, 1).contiguous()  # [B, 7, 7, D]
        latents = latents.view(-1, self.embedding_dim)         # [B*49, D]
        
        dist = (torch.sum(latents ** 2, dim=1, keepdim=True)
                + torch.sum(self.vq_layer.embedding ** 2, dim=1)
                - 2 * torch.matmul(latents, self.vq_layer.embedding.t()))
        
        indices = torch.argmin(dist, dim=1)  # [B*49]
        return indices.view(-1, 7, 7)        # [B, 7, 7] — 49 indices per observation
        
