"""PowerNet is an model architecture for learning power allocation in wireless networks. It is designed to be simple and efficient, while still achieving state-of-the-art performance on the problem of power allocation in wireless networks."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02b_models.powernet.ipynb.

# %% auto #0
__all__ = ['PowerNetMLP', 'PowerNetMasked', 'PowerNet', 'PowerCritic']

# %% ../../nbs/02b_models.powernet.ipynb #f690f80d
import torch
from torch import nn
from torch.nn import functional as F
from einops import rearrange
from torch.distributions import Bernoulli, Normal

from ..utils import channel

# %% ../../nbs/02b_models.powernet.ipynb #2601fbd8
class PowerNetMLP(nn.Module):
    def __init__(self, num_embeddings, embedding_dim, csi_dim, max_power):
        super().__init__()
        self.max_power = max_power
        self.embedding = nn.Embedding(num_embeddings, embedding_dim)
        
        # CSI is complex number → treat as 2 real values per agent
        self.net = nn.Sequential(
            nn.Linear(embedding_dim + csi_dim * 2, 128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.ReLU(),
        )
        self.schedule_head = nn.Linear(64, 1)   # binary send/no send
        self.power_head = nn.Linear(64, 1)       # power level

    def forward(self, message_indices, csi):
        # message_idx: [B] integer indices
        # csi: [B, csi_dim] complex → pass as [B, csi_dim*2] real

        msg_embed = self.embedding(message_indices)      # [B, 49, embedding_dim]
        msg_flat = msg_embed.flatten(1)                  # [B, 49 * embedding_dim]
        csi_real = torch.view_as_real(csi).flatten(-2)   # [B, csi_dim*2]
        x = torch.cat([msg_flat, csi_real], dim=-1)
        features = self.net(x)
        
        schedule = torch.sigmoid(self.schedule_head(features))        # [B, 1] ∈ (0,1)
        power = torch.sigmoid(self.power_head(features)) * self.max_power  # [B, 1] ∈ (0, P_max)
        
        return schedule, power

# %% ../../nbs/02b_models.powernet.ipynb #8c966fc1
class PowerNetMasked(nn.Module):
    def __init__(self, num_embeddings, embedding_dim, csi_dim, max_power,
                 nhead=4, num_layers=2):
        super().__init__()
        self.max_power = max_power
        self.embedding_dim = embedding_dim

        # Message token embedding
        self.msg_embedding = nn.Embedding(num_embeddings, embedding_dim)

        # Project CSI (complex → 2 reals) to embedding_dim to use as query token
        self.csi_proj = nn.Linear(csi_dim * 2, embedding_dim)

        # Transformer encoder
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=embedding_dim,
            nhead=nhead,
            dim_feedforward=256,
            dropout=0.1,
            batch_first=True
        )
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)

        # Output heads — operate on the CSI query token output
        self.schedule_head = nn.Linear(embedding_dim, 1)
        self.power_head = nn.Linear(embedding_dim, 1)

    def forward(self, message_indices, csi):
        """
        message_indices: [B, 49] — same message for all neighbors
        csi: [B, num_neighbors, csi_dim] complex — different per neighbor
        returns:
            schedule: [B, num_neighbors, 1]
            power:    [B, num_neighbors, 1]
        """
        B, num_neighbors, _ = csi.shape

        # Embed message tokens: [B, 49, D]
        msg_tokens = self.msg_embedding(message_indices.view(B, -1))

        # Project CSI to embedding dim: [B, num_neighbors, D]
        csi_real = torch.view_as_real(csi).flatten(-2)      # [B, num_neighbors, csi_dim*2]
        csi_tokens = self.csi_proj(csi_real)                 # [B, num_neighbors, D]

        # Process each neighbor separately but efficiently using batch dim
        # Expand message tokens for each neighbor: [B*num_neighbors, 49, D]
        msg_expanded = msg_tokens.unsqueeze(1).expand(
            -1, num_neighbors, -1, -1
        ).reshape(B * num_neighbors, 49, self.embedding_dim)

        # CSI token as first token (acts as query over message)
        # [B*num_neighbors, 1, D]
        csi_expanded = csi_tokens.reshape(B * num_neighbors, 1, self.embedding_dim)

        # Concatenate: CSI token + 49 message tokens → sequence of 50
        sequence = torch.cat([csi_expanded, msg_expanded], dim=1)  # [B*N, 50, D]

        # Transformer: CSI token attends to message tokens
        out = self.transformer(sequence)                     # [B*N, 50, D]

        # Take output at CSI token position (index 0)
        csi_out = out[:, 0, :]                               # [B*N, D]

        # Output heads
        schedule = torch.sigmoid(
            self.schedule_head(csi_out)
        ).view(B, num_neighbors, 1)                          # [B, num_neighbors, 1]

        power = torch.sigmoid(
            self.power_head(csi_out)
        ).view(B, num_neighbors, 1) * self.max_power         # [B, num_neighbors, 1]

        return schedule, power
    

# %% ../../nbs/02b_models.powernet.ipynb #fc8bdd9e
import math
class PowerNet(nn.Module):
    def __init__(self, num_embeddings, embedding_dim, csi_dim, max_power,
                 nhead=4, num_layers=2, lambda_pow=0.01, lambda_entropy=0.05, lambda_critic=0.05):
        super().__init__()
        self.max_power = max_power
        self.lambda_pow = lambda_pow
        self.lambda_entropy = lambda_entropy
        self.lambda_critic = lambda_critic
        self.embedding_dim = embedding_dim

        self.msg_embedding = nn.Embedding(num_embeddings, embedding_dim)
        self.csi_proj = nn.Linear(csi_dim * 2, embedding_dim)
        self.log_power_std = nn.Parameter(
            torch.tensor(math.log(max_power / 4.0))
            )


        # Self-attention over message tokens first
        msg_layer = nn.TransformerEncoderLayer(
            d_model=embedding_dim,
            nhead=nhead,
            dim_feedforward=256,
            dropout=0.1,
            batch_first=True
        )
        self.msg_transformer = nn.TransformerEncoder(msg_layer, num_layers=num_layers)

        # Cross-attention: CSI queries over message tokens
        self.cross_attn = nn.MultiheadAttention(
            embed_dim=embedding_dim,
            num_heads=nhead,
            batch_first=True
        )

        self.schedule_head = nn.Linear(embedding_dim, 1)
        self.power_head = nn.Linear(2*embedding_dim, 1)

    @property
    def power_std(self):
        return self.log_power_std.exp().clamp(1e-4, self.max_power)

    def forward(self, message_indices, csi):
        """
        message_indices: [B, 49]
        csi: [B, num_neighbors, csi_dim] complex
        returns:
            schedule: [B, num_neighbors, 1]
            power:    [B, num_neighbors, 1]
        """
        B, num_neighbors, _ = csi.shape

        # 1. Embed and contextualize message tokens with self-attention
        msg_tokens = self.msg_embedding(message_indices)     # [B, 49, D]
        msg_ctx = self.msg_transformer(msg_tokens)           # [B, 49, D]

        # 2. Project CSI to query vectors
        csi_real = torch.view_as_real(csi).flatten(-2)       # [B, num_neighbors, csi_dim*2]
        csi_query = self.csi_proj(csi_real)                  # [B, num_neighbors, D]

        # 3. Cross-attention: each neighbor's CSI queries over message tokens
        # Expand msg_ctx for each neighbor
        msg_expanded = msg_ctx.unsqueeze(1).expand(
            -1, num_neighbors, -1, -1
        ).reshape(B * num_neighbors, 49, self.embedding_dim) # [B*N, 49, D]

        csi_expanded = csi_query.reshape(
            B * num_neighbors, 1, self.embedding_dim
        )                                                     # [B*N, 1, D]

        # CSI is query, message tokens are keys and values
        # "given my channel quality, what parts of this message matter?"
        attended, _ = self.cross_attn(
            query=csi_expanded,                              # [B*N, 1, D]
            key=msg_expanded,                                # [B*N, 49, D]
            value=msg_expanded                               # [B*N, 49, D]
        )                                                    # [B*N, 1, D]

        # out = attended.squeeze(1)                            # [B*N, D]

        attended_msg = attended.squeeze(1)           # [B*N, D] — message relevance per neighbor
        csi_expanded_flat = csi_expanded.squeeze(1)  # [B*N, D] — channel representation
        
        # 4. Per-neighbor decisions
        schedule = torch.sigmoid(
            self.schedule_head(attended_msg)         # what does the message contain?
        ).view(B, num_neighbors, 1)

        power_input = torch.cat([attended_msg, csi_expanded_flat], dim=-1)  # [B*N, 2D]
        power = torch.sigmoid(
            self.power_head(power_input)             # how hard to deliver this message?
        ).view(B, num_neighbors, 1) * self.max_power

        return schedule, power

    def loss_fn(self, critic, reward, msg_indices, csi, schedule, power):
        """
        schedule: (B*T, N, 1) — sigmoid probabilities from PowerNet
        power:    (B*T, N, 1) — mean power from PowerNet
        """
        # ── Reward ────────────────────────────────────────────────────────
        # with torch.no_grad():
        #     pred_emb_no_msg = model.predict(ctx_emb, ctx_act, None)
        #     baseline_loss = (pred_emb_no_msg - tgt_emb).pow(2).mean()
        #     reward = baseline_loss - pred_loss                 # scalar

        # ── Critic ────────────────────────────────────────────────────────
        values = critic(msg_indices, csi)                      # (B*T, N, 1)
        reward_expanded = reward.expand_as(values)
        critic_loss = F.mse_loss(values, reward_expanded.detach())

        # Advantage per neighbor
        advantage = (reward_expanded - values).detach()        # (B*T, N, 1)

        # ── Schedule (discrete) — REINFORCE ───────────────────────────────
        schedule_dist = torch.distributions.Bernoulli(probs=schedule.clamp(1e-6, 1-1e-6))
        schedule_sample = (schedule > 0.5).float().detach()    # hard decision
        log_prob_schedule = schedule_dist.log_prob(schedule_sample)  # (B*T, N, 1)
        schedule_loss = -(advantage * log_prob_schedule).mean()

        # ── Power (continuous) — Gaussian policy ──────────────────────────
        power_dist = torch.distributions.Normal(
            loc=power,
            scale=self.power_std                               # learnable scalar std
        )
        power_sample = power_dist.rsample().clamp(0, self.max_power)
        log_prob_power = power_dist.log_prob(power_sample)     # (B*T, N, 1)

        # Power policy only matters when transmitting
        power_loss = -(advantage * log_prob_power * schedule_sample).mean()
        power_penalty = self.lambda_pow * (power * schedule_sample).mean()

        # ── Entropy bonuses ───────────────────────────────────────────────
        schedule_entropy = -self.lambda_entropy * schedule_dist.entropy().mean()
        power_entropy    = -self.lambda_entropy * power_dist.entropy().mean()

        # ── Total ─────────────────────────────────────────────────────────
        actor_loss = (schedule_loss + power_loss + 
                    power_penalty + schedule_entropy + power_entropy)
        tx_loss = actor_loss + self.lambda_critic * critic_loss

        return tx_loss, critic_loss, actor_loss


# %% ../../nbs/02b_models.powernet.ipynb #b83f97fc
class PowerCritic(nn.Module):
    def __init__(self, num_embeddings, embedding_dim, csi_dim, nhead=4, num_layers=2):
        super().__init__()
        self.embedding_dim = embedding_dim

        self.msg_embedding = nn.Embedding(num_embeddings, embedding_dim)
        self.csi_proj = nn.Linear(csi_dim * 2, embedding_dim)

        # Self-attention over message tokens (same structure as actor)
        msg_layer = nn.TransformerEncoderLayer(
            d_model=embedding_dim,
            nhead=nhead,
            dim_feedforward=256,
            dropout=0.1,
            batch_first=True
        )
        self.msg_transformer = nn.TransformerEncoder(msg_layer, num_layers=num_layers)

        # Cross-attention: CSI queries over message tokens
        self.cross_attn = nn.MultiheadAttention(
            embed_dim=embedding_dim,
            num_heads=nhead,
            batch_first=True
        )

        # Value Head: Estimates the expected reward per neighbor given (CSI + Message)
        self.value_head = nn.Linear(2 * embedding_dim, 1)

    def forward(self, message_indices, csi):
        """
        message_indices: [B, 49]
        csi: [B, num_neighbors, csi_dim] complex
        returns:
            values: [B, num_neighbors, 1] - Expected reward baseline per neighbor
        """
        B, num_neighbors, _ = csi.shape

        # 1. Message Context
        msg_tokens = self.msg_embedding(message_indices)     # [B, 49, D]
        msg_ctx = self.msg_transformer(msg_tokens)           # [B, 49, D]

        # 2. CSI Query
        csi_real = torch.view_as_real(csi).flatten(-2)       # [B, num_neighbors, csi_dim*2]
        csi_query = self.csi_proj(csi_real)                  # [B, num_neighbors, D]

        # 3. Cross-Attention
        msg_expanded = msg_ctx.unsqueeze(1).expand(
            -1, num_neighbors, -1, -1
        ).reshape(B * num_neighbors, 49, self.embedding_dim) # [B*N, 49, D]

        csi_expanded = csi_query.reshape(
            B * num_neighbors, 1, self.embedding_dim
        )                                                     # [B*N, 1, D]

        attended, _ = self.cross_attn(
            query=csi_expanded,
            key=msg_expanded,
            value=msg_expanded
        )                                                     # [B*N, 1, D]

        attended_msg = attended.squeeze(1)                    # [B*N, D]
        csi_expanded_flat = csi_expanded.squeeze(1)            # [B*N, D]

        # 4. Value Estimation
        value_input = torch.cat([attended_msg, csi_expanded_flat], dim=-1)  # [B*N, 2D]
        
        # Linear layer outputs unconstrained value estimate per neighbor
        values = self.value_head(value_input).view(B, num_neighbors, 1)     # [B, num_neighbors, 1]

        return values
