"""PowerNet is an MLP-based architecture for learning power allocation in wireless networks. It is designed to be simple and efficient, while still achieving state-of-the-art performance on the problem of power allocation in wireless networks."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02b_models.powernet.ipynb.

# %% auto #0
__all__ = ['PowerNetMLP', 'PowerNetMasked', 'PowerNet']

# %% ../../nbs/02b_models.powernet.ipynb #032095ed
import torch
from torch import nn
from torch.nn import functional as F
from einops import rearrange

from ..utils import channel

# %% ../../nbs/02b_models.powernet.ipynb #3664f7e5
class PowerNetMLP(nn.Module):
    def __init__(self, num_embeddings, embedding_dim, csi_dim, max_power):
        super().__init__()
        self.max_power = max_power
        self.embedding = nn.Embedding(num_embeddings, embedding_dim)
        
        # CSI is complex number → treat as 2 real values per agent
        self.net = nn.Sequential(
            nn.Linear(embedding_dim + csi_dim * 2, 128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.ReLU(),
        )
        self.schedule_head = nn.Linear(64, 1)   # binary send/no send
        self.power_head = nn.Linear(64, 1)       # power level

    def forward(self, message_indices, csi):
        # message_idx: [B] integer indices
        # csi: [B, csi_dim] complex → pass as [B, csi_dim*2] real

        msg_embed = self.embedding(message_indices)      # [B, 49, embedding_dim]
        msg_flat = msg_embed.flatten(1)                  # [B, 49 * embedding_dim]
        csi_real = torch.view_as_real(csi).flatten(-2)   # [B, csi_dim*2]
        x = torch.cat([msg_flat, csi_real], dim=-1)
        features = self.net(x)
        
        schedule = torch.sigmoid(self.schedule_head(features))        # [B, 1] ∈ (0,1)
        power = torch.sigmoid(self.power_head(features)) * self.max_power  # [B, 1] ∈ (0, P_max)
        
        return schedule, power

# %% ../../nbs/02b_models.powernet.ipynb #5fa6c85a
class PowerNetMasked(nn.Module):
    def __init__(self, num_embeddings, embedding_dim, csi_dim, max_power,
                 nhead=4, num_layers=2):
        super().__init__()
        self.max_power = max_power
        self.embedding_dim = embedding_dim

        # Message token embedding
        self.msg_embedding = nn.Embedding(num_embeddings, embedding_dim)

        # Project CSI (complex → 2 reals) to embedding_dim to use as query token
        self.csi_proj = nn.Linear(csi_dim * 2, embedding_dim)

        # Transformer encoder
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=embedding_dim,
            nhead=nhead,
            dim_feedforward=256,
            dropout=0.1,
            batch_first=True
        )
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)

        # Output heads — operate on the CSI query token output
        self.schedule_head = nn.Linear(embedding_dim, 1)
        self.power_head = nn.Linear(embedding_dim, 1)

    def forward(self, message_indices, csi):
        """
        message_indices: [B, 49] — same message for all neighbors
        csi: [B, num_neighbors, csi_dim] complex — different per neighbor
        returns:
            schedule: [B, num_neighbors, 1]
            power:    [B, num_neighbors, 1]
        """
        B, num_neighbors, _ = csi.shape

        # Embed message tokens: [B, 49, D]
        msg_tokens = self.msg_embedding(message_indices.view(B, -1))

        # Project CSI to embedding dim: [B, num_neighbors, D]
        csi_real = torch.view_as_real(csi).flatten(-2)      # [B, num_neighbors, csi_dim*2]
        csi_tokens = self.csi_proj(csi_real)                 # [B, num_neighbors, D]

        # Process each neighbor separately but efficiently using batch dim
        # Expand message tokens for each neighbor: [B*num_neighbors, 49, D]
        msg_expanded = msg_tokens.unsqueeze(1).expand(
            -1, num_neighbors, -1, -1
        ).reshape(B * num_neighbors, 49, self.embedding_dim)

        # CSI token as first token (acts as query over message)
        # [B*num_neighbors, 1, D]
        csi_expanded = csi_tokens.reshape(B * num_neighbors, 1, self.embedding_dim)

        # Concatenate: CSI token + 49 message tokens → sequence of 50
        sequence = torch.cat([csi_expanded, msg_expanded], dim=1)  # [B*N, 50, D]

        # Transformer: CSI token attends to message tokens
        out = self.transformer(sequence)                     # [B*N, 50, D]

        # Take output at CSI token position (index 0)
        csi_out = out[:, 0, :]                               # [B*N, D]

        # Output heads
        schedule = torch.sigmoid(
            self.schedule_head(csi_out)
        ).view(B, num_neighbors, 1)                          # [B, num_neighbors, 1]

        power = torch.sigmoid(
            self.power_head(csi_out)
        ).view(B, num_neighbors, 1) * self.max_power         # [B, num_neighbors, 1]

        return schedule, power
    

# %% ../../nbs/02b_models.powernet.ipynb #468f8334
class PowerNet(nn.Module):
    def __init__(self, num_embeddings, embedding_dim, csi_dim, max_power,
                 nhead=4, num_layers=2):
        super().__init__()
        self.max_power = max_power
        self.embedding_dim = embedding_dim

        self.msg_embedding = nn.Embedding(num_embeddings, embedding_dim)
        self.csi_proj = nn.Linear(csi_dim * 2, embedding_dim)

        # Self-attention over message tokens first
        msg_layer = nn.TransformerEncoderLayer(
            d_model=embedding_dim,
            nhead=nhead,
            dim_feedforward=256,
            dropout=0.1,
            batch_first=True
        )
        self.msg_transformer = nn.TransformerEncoder(msg_layer, num_layers=num_layers)

        # Cross-attention: CSI queries over message tokens
        self.cross_attn = nn.MultiheadAttention(
            embed_dim=embedding_dim,
            num_heads=nhead,
            batch_first=True
        )

        self.schedule_head = nn.Linear(embedding_dim, 1)
        self.power_head = nn.Linear(2*embedding_dim, 1)

    def forward(self, message_indices, csi):
        """
        message_indices: [B, 49]
        csi: [B, num_neighbors, csi_dim] complex
        returns:
            schedule: [B, num_neighbors, 1]
            power:    [B, num_neighbors, 1]
        """
        B, num_neighbors, _ = csi.shape

        # 1. Embed and contextualize message tokens with self-attention
        msg_tokens = self.msg_embedding(message_indices)     # [B, 49, D]
        msg_ctx = self.msg_transformer(msg_tokens)           # [B, 49, D]

        # 2. Project CSI to query vectors
        csi_real = torch.view_as_real(csi).flatten(-2)       # [B, num_neighbors, csi_dim*2]
        csi_query = self.csi_proj(csi_real)                  # [B, num_neighbors, D]

        # 3. Cross-attention: each neighbor's CSI queries over message tokens
        # Expand msg_ctx for each neighbor
        msg_expanded = msg_ctx.unsqueeze(1).expand(
            -1, num_neighbors, -1, -1
        ).reshape(B * num_neighbors, 49, self.embedding_dim) # [B*N, 49, D]

        csi_expanded = csi_query.reshape(
            B * num_neighbors, 1, self.embedding_dim
        )                                                     # [B*N, 1, D]

        # CSI is query, message tokens are keys and values
        # "given my channel quality, what parts of this message matter?"
        attended, _ = self.cross_attn(
            query=csi_expanded,                              # [B*N, 1, D]
            key=msg_expanded,                                # [B*N, 49, D]
            value=msg_expanded                               # [B*N, 49, D]
        )                                                    # [B*N, 1, D]

        # out = attended.squeeze(1)                            # [B*N, D]

        attended_msg = attended.squeeze(1)           # [B*N, D] — message relevance per neighbor
        csi_expanded_flat = csi_expanded.squeeze(1)  # [B*N, D] — channel representation
        
        # 4. Per-neighbor decisions
        schedule = torch.sigmoid(
            self.schedule_head(attended_msg)         # what does the message contain?
        ).view(B, num_neighbors, 1)


        power_input = torch.cat([attended_msg, csi_expanded_flat], dim=-1)  # [B*N, 2D]
        power = torch.sigmoid(
            self.power_head(power_input)             # how hard to deliver this message?
        ).view(B, num_neighbors, 1) * self.max_power

        return schedule, power
    

    # def loss_fn(self, model, ctx_len, ctx_emb, ctx_act, msg_indices, tgt_emb, schedule, power, pred_loss):
    #     with torch.no_grad():
    #         pred_emb_zero_msg = model.predict(ctx_emb, ctx_act, None) # pred with no comm.

    #         msg_indices = rearrange(msg_indices, "(b t) msg_dim -> b t msg_dim", msg_dim=49)   # (B, T, 49)
    #         ctx_msg = msg_indices[:, :ctx_len] # (B, ctx_len, msg_dim)
    #         pred_emb_perfect_msg = model.predict(ctx_emb, ctx_act, ctx_msg) # pred with perfect comm.

    #         perfect_loss = (pred_emb_perfect_msg - tgt_emb).pow(2).mean()
    #         value = (pred_emb_zero_msg - tgt_emb).pow(2).mean() - perfect_loss
    #         qulity = perfect_loss - pred_loss

    #     tx_loss =   -self.lambda_value * value * (schedule.float().mean()) + \
    #                 -self.lambda_quality * qulity * power.mean() + \
    #                 self.lambda_pow * power.mean() * (schedule.float().mean()) + \
    #                 self.lambda_send * (schedule.float().mean())
        
    #     return tx_loss
    

    def loss_fn(self, model, B, ctx_len, ctx_emb, ctx_act, msg_indices, tgt_emb, 
            schedule, power, csi_flat, pred_loss, lambda_value, lambda_pow, lambda_send, device):
        with torch.no_grad():
            # Baseline: prediction with no message
            received_msg = channel(
                schedule, power, msg_indices, csi_flat, device=device, no_comm=True
            )  # (B*T, 49)
            received_msg = rearrange(
                received_msg, "(b t) msg_dim -> b t msg_dim", b=B, t=ctx_len
            )  # (B, T, 49)
            ctx_msg = received_msg[:, :ctx_len]                # (B, T, 49) — raw indices, embedded inside predictor
            
            pred_emb_no_msg = model.predict(ctx_emb, ctx_act, ctx_msg)
            baseline_loss = (pred_emb_no_msg - tgt_emb).pow(2).mean()
            # How much did transmitting actually help?
            # Positive = transmission helped, Negative = transmission hurt
            comm_gain = baseline_loss - pred_loss  # scalar

        s_mean = schedule.mean()   # (0,1) — how often we transmit
        p_mean = power.mean()      # (0, P_max) — average power used

        # 1. Reward scheduling when communication improves prediction
        reward_term = -lambda_value * comm_gain * s_mean

        # 2. Penalize power consumption (only when transmitting)
        power_term = lambda_pow * p_mean * s_mean

        # 3. Sparsity: penalize transmitting at all (encourages selective sending)
        sparsity_term = lambda_send * s_mean

        tx_loss = reward_term + power_term + sparsity_term
        return {
            "reward_term_loss": reward_term,
            "power_term_loss": power_term,
            "sparsity_term_loss": sparsity_term,
            "tx_loss": tx_loss,
            "base_line_loss": baseline_loss,
            "comm_gain": comm_gain,
            "schedule_mean": s_mean,
            "power_mean": p_mean
        }
    
